param(
  [Parameter(Mandatory)][string]$RepoRoot,
  [string]$MigrationId = "",
  [switch]$LinkProject,
  [string]$ProjectRef = "",
  [switch]$ApplyRemote
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function EnsureDir([string]$p) { if (-not (Test-Path -LiteralPath $p)) { New-Item -ItemType Directory -Path $p -Force | Out-Null } }
function WriteUtf8NoBomIfChanged([string]$Path, [string]$Content) {
  $dir = Split-Path -Parent $Path
  if ($dir) { EnsureDir $dir }
  $enc = New-Object System.Text.UTF8Encoding($false)
  $existing = $null
  if (Test-Path -LiteralPath $Path) { $existing = Get-Content -Raw -LiteralPath $Path -Encoding UTF8 }
  if ($existing -ne $Content) {
    [IO.File]::WriteAllText($Path, $Content, $enc)
    Write-Host ("[OK] WROTE " + $Path) -ForegroundColor DarkGreen
  } else {
    Write-Host ("[OK] NO-CHANGE " + $Path) -ForegroundColor DarkCyan
  }
}

if (-not (Test-Path -LiteralPath $RepoRoot)) { throw "RepoRoot not found: $RepoRoot" }
Set-Location $RepoRoot

$mgDir = Join-Path $RepoRoot "supabase\migrations"
EnsureDir $mgDir

if (-not $MigrationId) { $MigrationId = (Get-Date).ToUniversalTime().ToString("yyyyMMddHHmmss") }
$mgPath = Join-Path $mgDir ("{0}_rgsr_profile_menu_geometry_templates_v1.sql" -f $MigrationId)

$sqlLines = New-Object System.Collections.Generic.List[string]

$sqlLines.Add('-- ============================================================')
$sqlLines.Add('-- RGSR: Profile Menu + Seat Overrides + Geometry Templates (V1)')
$sqlLines.Add('-- Canonical: profile actions, team actions, geometry library/templates')
$sqlLines.Add('-- RLS: private by default; lab-shared only when seat allows; published templates readable')
$sqlLines.Add('-- ============================================================')
$sqlLines.Add('')
$sqlLines.Add('begin;')
$sqlLines.Add('')
$sqlLines.Add('create extension if not exists pgcrypto;')
$sqlLines.Add('')
$sqlLines.Add('-- 1) Capabilities (geometry + access controls for profile menu)')
$sqlLines.Add('insert into rgsr.capabilities (capability_id, description) values')
$sqlLines.Add('  (''GEOMETRY_VIEW'',          ''View geometry library (private + lab + published)''),')
$sqlLines.Add('  (''GEOMETRY_CREATE'',        ''Create private geometry sets''),')
$sqlLines.Add('  (''GEOMETRY_EDIT'',          ''Edit geometry sets you own (or lab-permitted)''),')
$sqlLines.Add('  (''GEOMETRY_SHARE_LAB'',     ''Share geometry sets into LAB lane''),')
$sqlLines.Add('  (''GEOMETRY_TEMPLATE'',      ''Mark geometry sets as templates''),')
$sqlLines.Add('  (''GEOMETRY_PUBLISH'',       ''Publish geometry templates (PUBLISHED lane)''),')
$sqlLines.Add('  (''SEAT_GRANT'',             ''Grant/revoke per-member capability overrides inside a lab'')')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- 2) Seed plan capabilities (baseline; you can tighten later)')
$sqlLines.Add('-- Everyone who is authenticated can VIEW geometry library:')
$sqlLines.Add('insert into rgsr.plan_capabilities(plan_id, capability_id, enabled) values')
$sqlLines.Add('  (''OBSERVER_FREE'',''GEOMETRY_VIEW'', true),')
$sqlLines.Add('  (''RESEARCHER_PRO'',''GEOMETRY_VIEW'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''GEOMETRY_VIEW'', true),')
$sqlLines.Add('  (''INSTITUTION'',''GEOMETRY_VIEW'', true)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- Create/edit rights by plan:')
$sqlLines.Add('insert into rgsr.plan_capabilities(plan_id, capability_id, enabled) values')
$sqlLines.Add('  (''RESEARCHER_PRO'',''GEOMETRY_CREATE'', true),')
$sqlLines.Add('  (''RESEARCHER_PRO'',''GEOMETRY_EDIT'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''GEOMETRY_CREATE'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''GEOMETRY_EDIT'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''GEOMETRY_SHARE_LAB'', true),')
$sqlLines.Add('  (''INSTITUTION'',''GEOMETRY_CREATE'', true),')
$sqlLines.Add('  (''INSTITUTION'',''GEOMETRY_EDIT'', true),')
$sqlLines.Add('  (''INSTITUTION'',''GEOMETRY_SHARE_LAB'', true),')
$sqlLines.Add('  (''INSTITUTION'',''GEOMETRY_TEMPLATE'', true),')
$sqlLines.Add('  (''INSTITUTION'',''GEOMETRY_PUBLISH'', true)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- 3) Seed seat (lab role) capabilities')
$sqlLines.Add('-- VIEWER: view only; MEMBER: create/edit own; ADMIN/OWNER: manage/share/templates/publish')
$sqlLines.Add('insert into rgsr.lab_role_capabilities (lab_role, capability_id, enabled) values')
$sqlLines.Add('  (''VIEWER'',''GEOMETRY_VIEW'', true),')
$sqlLines.Add('  (''MEMBER'',''GEOMETRY_VIEW'', true),')
$sqlLines.Add('  (''MEMBER'',''GEOMETRY_CREATE'', true),')
$sqlLines.Add('  (''MEMBER'',''GEOMETRY_EDIT'', true),')
$sqlLines.Add('  (''ADMIN'',''GEOMETRY_VIEW'', true),')
$sqlLines.Add('  (''ADMIN'',''GEOMETRY_CREATE'', true),')
$sqlLines.Add('  (''ADMIN'',''GEOMETRY_EDIT'', true),')
$sqlLines.Add('  (''ADMIN'',''GEOMETRY_SHARE_LAB'', true),')
$sqlLines.Add('  (''ADMIN'',''GEOMETRY_TEMPLATE'', true),')
$sqlLines.Add('  (''OWNER'',''GEOMETRY_VIEW'', true),')
$sqlLines.Add('  (''OWNER'',''GEOMETRY_CREATE'', true),')
$sqlLines.Add('  (''OWNER'',''GEOMETRY_EDIT'', true),')
$sqlLines.Add('  (''OWNER'',''GEOMETRY_SHARE_LAB'', true),')
$sqlLines.Add('  (''OWNER'',''GEOMETRY_TEMPLATE'', true),')
$sqlLines.Add('  (''OWNER'',''GEOMETRY_PUBLISH'', true),')
$sqlLines.Add('  (''ADMIN'',''SEAT_GRANT'', true),')
$sqlLines.Add('  (''OWNER'',''SEAT_GRANT'', true)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- 4) Per-member overrides (granular access controls inside a lab)')
$sqlLines.Add('create table if not exists rgsr.lab_member_capability_overrides (')
$sqlLines.Add('  lab_id         uuid not null references rgsr.labs(lab_id) on delete cascade,')
$sqlLines.Add('  user_id        uuid not null references auth.users(id) on delete cascade,')
$sqlLines.Add('  capability_id  text not null references rgsr.capabilities(capability_id) on delete cascade,')
$sqlLines.Add('  enabled        boolean not null,')
$sqlLines.Add('  created_by     uuid not null references auth.users(id) on delete cascade,')
$sqlLines.Add('  created_at     timestamptz not null default now(),')
$sqlLines.Add('  updated_at     timestamptz not null default now(),')
$sqlLines.Add('  primary key (lab_id, user_id, capability_id)')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.tg_touch_updated_at()')
$sqlLines.Add('returns trigger language plpgsql as $$')
$sqlLines.Add('begin')
$sqlLines.Add('  new.updated_at = now();')
$sqlLines.Add('  return new;')
$sqlLines.Add('end $$;')
$sqlLines.Add('')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_trigger where tgname = ''tr_lab_member_overrides_touch'') then')
$sqlLines.Add('    create trigger tr_lab_member_overrides_touch')
$sqlLines.Add('    before update on rgsr.lab_member_capability_overrides')
$sqlLines.Add('    for each row execute function rgsr.tg_touch_updated_at();')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- Effective seat capability: overrides > seat role caps > sys admin')
$sqlLines.Add('create or replace function rgsr.has_lab_capability_effective(p_lab uuid, p_user uuid, p_cap text)')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select rgsr.is_sys_admin()')
$sqlLines.Add('  or coalesce((')
$sqlLines.Add('    select o.enabled')
$sqlLines.Add('    from rgsr.lab_member_capability_overrides o')
$sqlLines.Add('    where o.lab_id = p_lab and o.user_id = p_user and o.capability_id = p_cap')
$sqlLines.Add('  ), (')
$sqlLines.Add('    select exists (')
$sqlLines.Add('      select 1 from rgsr.lab_role_capabilities lrc')
$sqlLines.Add('      where lrc.lab_role = rgsr.current_lab_role(p_lab)')
$sqlLines.Add('        and lrc.capability_id = p_cap')
$sqlLines.Add('        and lrc.enabled')
$sqlLines.Add('    )')
$sqlLines.Add('  ));')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('-- Convenience: current user + lab')
$sqlLines.Add('create or replace function rgsr.me_has_lab_capability(p_lab uuid, p_cap text)')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select rgsr.has_lab_capability_effective(p_lab, auth.uid(), p_cap);')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('-- 5) Geometry library: sets with JSON definition, lane-aware')
$sqlLines.Add('create table if not exists rgsr.geometry_sets (')
$sqlLines.Add('  geometry_id    uuid primary key default gen_random_uuid(),')
$sqlLines.Add('  name           text not null,')
$sqlLines.Add('  description    text,')
$sqlLines.Add('  lane           rgsr.rgsr_lane not null default ''PRIVATE'',')
$sqlLines.Add('  is_template    boolean not null default false,')
$sqlLines.Add('  engine_code    text not null default ''RGSR'',')
$sqlLines.Add('  owner_id       uuid not null references auth.users(id) on delete cascade,')
$sqlLines.Add('  lab_id         uuid references rgsr.labs(lab_id) on delete set null,')
$sqlLines.Add('  geometry_json  jsonb not null,')
$sqlLines.Add('  dims_json      jsonb,')
$sqlLines.Add('  created_at     timestamptz not null default now(),')
$sqlLines.Add('  updated_at     timestamptz not null default now()')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_trigger where tgname = ''tr_geometry_sets_touch'') then')
$sqlLines.Add('    create trigger tr_geometry_sets_touch')
$sqlLines.Add('    before update on rgsr.geometry_sets')
$sqlLines.Add('    for each row execute function rgsr.tg_touch_updated_at();')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- Forward-only lane for geometry (reuse lane_rank)')
$sqlLines.Add('create or replace function rgsr.tg_geometry_lane_forward_only()')
$sqlLines.Add('returns trigger language plpgsql as $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if (tg_op = ''UPDATE'') then')
$sqlLines.Add('    if rgsr.lane_rank(new.lane) < rgsr.lane_rank(old.lane) then')
$sqlLines.Add('      raise exception ''Geometry lane is forward-only: % -> % is not allowed'', old.lane, new.lane')
$sqlLines.Add('        using errcode = ''check_violation'';')
$sqlLines.Add('    end if;')
$sqlLines.Add('  end if;')
$sqlLines.Add('  return new;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_trigger where tgname = ''tr_geometry_lane_forward_only'') then')
$sqlLines.Add('    create trigger tr_geometry_lane_forward_only')
$sqlLines.Add('    before update of lane on rgsr.geometry_sets')
$sqlLines.Add('    for each row execute function rgsr.tg_geometry_lane_forward_only();')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- 6) Geometry read/write rules')
$sqlLines.Add('create or replace function rgsr.can_read_geometry(p_lane rgsr.rgsr_lane, p_owner uuid, p_lab uuid)')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select rgsr.is_sys_admin()')
$sqlLines.Add('  or case p_lane')
$sqlLines.Add('    when ''PUBLISHED'' then true')
$sqlLines.Add('    when ''PRIVATE'' then (auth.uid() = p_owner) and rgsr.has_capability(''GEOMETRY_VIEW'')')
$sqlLines.Add('    when ''LAB'' then (p_lab is not null and rgsr.is_lab_member(p_lab) and rgsr.has_capability(''GEOMETRY_VIEW''))')
$sqlLines.Add('    when ''REVIEW'' then (p_lab is not null and rgsr.is_lab_member(p_lab) and rgsr.has_capability(''GEOMETRY_VIEW''))')
$sqlLines.Add('  end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.can_write_geometry_target(p_lane rgsr.rgsr_lane, p_lab uuid)')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select rgsr.is_sys_admin()')
$sqlLines.Add('  or case p_lane')
$sqlLines.Add('    when ''PRIVATE'' then rgsr.has_capability(''GEOMETRY_CREATE'')')
$sqlLines.Add('    when ''LAB'' then (p_lab is not null and rgsr.me_has_lab_capability(p_lab, ''GEOMETRY_SHARE_LAB'') and rgsr.has_capability(''GEOMETRY_CREATE''))')
$sqlLines.Add('    when ''REVIEW'' then (p_lab is not null and rgsr.me_has_lab_capability(p_lab, ''GEOMETRY_SHARE_LAB'') and rgsr.has_capability(''GEOMETRY_CREATE''))')
$sqlLines.Add('    when ''PUBLISHED'' then (rgsr.has_capability(''GEOMETRY_PUBLISH''))')
$sqlLines.Add('  end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('-- 7) RLS: geometry library is private by default')
$sqlLines.Add('alter table rgsr.geometry_sets enable row level security;')
$sqlLines.Add('alter table rgsr.lab_member_capability_overrides enable row level security;')
$sqlLines.Add('')
$sqlLines.Add('-- geometry select')
$sqlLines.Add('drop policy if exists gs_select on rgsr.geometry_sets;')
$sqlLines.Add('create policy gs_select on rgsr.geometry_sets for select to authenticated')
$sqlLines.Add('using (rgsr.can_read_geometry(lane, owner_id, lab_id));')
$sqlLines.Add('')
$sqlLines.Add('-- geometry insert (must be owner; lane target must be allowed; lab_id must be member if present)')
$sqlLines.Add('drop policy if exists gs_insert on rgsr.geometry_sets;')
$sqlLines.Add('create policy gs_insert on rgsr.geometry_sets for insert to authenticated')
$sqlLines.Add('with check (')
$sqlLines.Add('  owner_id = auth.uid()')
$sqlLines.Add('  and rgsr.can_write_geometry_target(lane, lab_id)')
$sqlLines.Add('  and (lab_id is null or rgsr.is_lab_member(lab_id))')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- geometry update (owner or lab-admin; lane changes still forward-only by trigger)')
$sqlLines.Add('drop policy if exists gs_update on rgsr.geometry_sets;')
$sqlLines.Add('create policy gs_update on rgsr.geometry_sets for update to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or owner_id = auth.uid()')
$sqlLines.Add('  or (lab_id is not null and rgsr.me_has_lab_capability(lab_id, ''GEOMETRY_EDIT''))')
$sqlLines.Add(')')
$sqlLines.Add('with check (')
$sqlLines.Add('  rgsr.can_write_geometry_target(lane, lab_id)')
$sqlLines.Add('  and (lab_id is null or rgsr.is_lab_member(lab_id))')
$sqlLines.Add('  and (')
$sqlLines.Add('    (is_template = false)')
$sqlLines.Add('    or (is_template = true and rgsr.has_capability(''GEOMETRY_TEMPLATE''))')
$sqlLines.Add('  )')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- geometry delete (owner or lab-admin)')
$sqlLines.Add('drop policy if exists gs_delete on rgsr.geometry_sets;')
$sqlLines.Add('create policy gs_delete on rgsr.geometry_sets for delete to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or owner_id = auth.uid()')
$sqlLines.Add('  or (lab_id is not null and rgsr.me_has_lab_capability(lab_id, ''GEOMETRY_EDIT''))')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- overrides: only seat-granters (ADMIN/OWNER) can view or change overrides in their lab')
$sqlLines.Add('drop policy if exists ovr_select on rgsr.lab_member_capability_overrides;')
$sqlLines.Add('create policy ovr_select on rgsr.lab_member_capability_overrides for select to authenticated')
$sqlLines.Add('using (rgsr.is_sys_admin() or rgsr.me_has_lab_capability(lab_id, ''SEAT_GRANT''));')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists ovr_insert on rgsr.lab_member_capability_overrides;')
$sqlLines.Add('create policy ovr_insert on rgsr.lab_member_capability_overrides for insert to authenticated')
$sqlLines.Add('with check (rgsr.is_sys_admin() or rgsr.me_has_lab_capability(lab_id, ''SEAT_GRANT''));')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists ovr_update on rgsr.lab_member_capability_overrides;')
$sqlLines.Add('create policy ovr_update on rgsr.lab_member_capability_overrides for update to authenticated')
$sqlLines.Add('using (rgsr.is_sys_admin() or rgsr.me_has_lab_capability(lab_id, ''SEAT_GRANT''))')
$sqlLines.Add('with check (rgsr.is_sys_admin() or rgsr.me_has_lab_capability(lab_id, ''SEAT_GRANT''));')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists ovr_delete on rgsr.lab_member_capability_overrides;')
$sqlLines.Add('create policy ovr_delete on rgsr.lab_member_capability_overrides for delete to authenticated')
$sqlLines.Add('using (rgsr.is_sys_admin() or rgsr.me_has_lab_capability(lab_id, ''SEAT_GRANT''));')
$sqlLines.Add('')
$sqlLines.Add('-- 8) Profile Menu RPCs (for UI dropdown)')
$sqlLines.Add('create or replace function rgsr.get_my_profile_menu()')
$sqlLines.Add('returns jsonb')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select jsonb_build_object(')
$sqlLines.Add('    ''user_id'', up.user_id,')
$sqlLines.Add('    ''display_name'', up.display_name,')
$sqlLines.Add('    ''role_id'', up.role_id,')
$sqlLines.Add('    ''plan_id'', up.plan_id,')
$sqlLines.Add('    ''labs'', (')
$sqlLines.Add('      select coalesce(jsonb_agg(jsonb_build_object(')
$sqlLines.Add('        ''lab_id'', l.lab_id,')
$sqlLines.Add('        ''name'', l.name,')
$sqlLines.Add('        ''seat_role'', rgsr.current_lab_role(l.lab_id),')
$sqlLines.Add('        ''can_team_manage'', rgsr.me_has_lab_capability(l.lab_id, ''TEAM_MANAGE''),')
$sqlLines.Add('        ''can_team_invite'', rgsr.me_has_lab_capability(l.lab_id, ''TEAM_INVITE''),')
$sqlLines.Add('        ''can_seat_grant'', rgsr.me_has_lab_capability(l.lab_id, ''SEAT_GRANT''),')
$sqlLines.Add('        ''can_geometry_share_lab'', rgsr.me_has_lab_capability(l.lab_id, ''GEOMETRY_SHARE_LAB''),')
$sqlLines.Add('        ''can_geometry_edit'', rgsr.me_has_lab_capability(l.lab_id, ''GEOMETRY_EDIT'')')
$sqlLines.Add('      ) order by l.created_at), ''[]''::jsonb)')
$sqlLines.Add('      from rgsr.labs l')
$sqlLines.Add('      where exists (select 1 from rgsr.lab_members lm where lm.lab_id = l.lab_id and lm.user_id = auth.uid())')
$sqlLines.Add('         or l.owner_id = auth.uid()')
$sqlLines.Add('    ),')
$sqlLines.Add('    ''capabilities'', jsonb_build_object(')
$sqlLines.Add('      ''profile_edit'', rgsr.has_capability(''PROFILE_EDIT''),')
$sqlLines.Add('      ''geometry_view'', rgsr.has_capability(''GEOMETRY_VIEW''),')
$sqlLines.Add('      ''geometry_create'', rgsr.has_capability(''GEOMETRY_CREATE''),')
$sqlLines.Add('      ''geometry_template'', rgsr.has_capability(''GEOMETRY_TEMPLATE''),')
$sqlLines.Add('      ''geometry_publish'', rgsr.has_capability(''GEOMETRY_PUBLISH'')')
$sqlLines.Add('    )')
$sqlLines.Add('  )')
$sqlLines.Add('  from rgsr.user_profiles up')
$sqlLines.Add('  where up.user_id = auth.uid();')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.update_my_profile(p_display_name text)')
$sqlLines.Add('returns void')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not rgsr.has_capability(''PROFILE_EDIT'') then')
$sqlLines.Add('    raise exception ''not authorized'' using errcode = ''insufficient_privilege'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('  update rgsr.user_profiles')
$sqlLines.Add('  set display_name = nullif(trim(p_display_name), '''')')
$sqlLines.Add('  where user_id = auth.uid();')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('commit;')
$sqlLines.Add('')
$sqlLines.Add('-- ============================================================')
$sqlLines.Add('-- End migration')
$sqlLines.Add('-- ============================================================')

$sql = ($sqlLines -join "`r`n") + "`r`n"
WriteUtf8NoBomIfChanged $mgPath $sql
Write-Host ("[OK] MIGRATION READY: " + $mgPath) -ForegroundColor Green

if ($LinkProject) {
  if (-not $ProjectRef) {
    Write-Host "[NOTE] Paste Supabase Project Ref (Settings -> General -> Project Ref)" -ForegroundColor Yellow
    $ProjectRef = Read-Host "ProjectRef"
  }
  if (-not $ProjectRef) { throw "ProjectRef is required for link." }
  supabase link --project-ref $ProjectRef
}

if ($ApplyRemote) {
  supabase db push
}

Write-Host "✅ RGSR PROFILE MENU + GEOMETRY TEMPLATES PIPELINE COMPLETE" -ForegroundColor Green

