param(
  [Parameter(Mandatory)][string]$RepoRoot,
  [string]$MigrationId = "",
  [switch]$LinkProject,
  [string]$ProjectRef = "",
  [switch]$ApplyRemote
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function EnsureDir([string]$p) { if (-not (Test-Path -LiteralPath $p)) { New-Item -ItemType Directory -Path $p -Force | Out-Null } }
function WriteUtf8NoBomIfChanged([string]$Path, [string]$Content) {
  $dir = Split-Path -Parent $Path
  if ($dir) { EnsureDir $dir }
  $enc = New-Object System.Text.UTF8Encoding($false)
  $existing = $null
  if (Test-Path -LiteralPath $Path) { $existing = Get-Content -Raw -LiteralPath $Path -Encoding UTF8 }
  if ($existing -ne $Content) {
    [IO.File]::WriteAllText($Path, $Content, $enc)
    Write-Host ("[OK] WROTE " + $Path) -ForegroundColor DarkGreen
  } else {
    Write-Host ("[OK] NO-CHANGE " + $Path) -ForegroundColor DarkCyan
  }
}

if (-not (Test-Path -LiteralPath $RepoRoot)) { throw "RepoRoot not found: $RepoRoot" }
Set-Location $RepoRoot

$mgDir = Join-Path $RepoRoot "supabase\migrations"
EnsureDir $mgDir

if (-not $MigrationId) { $MigrationId = (Get-Date).ToUniversalTime().ToString("yyyyMMddHHmmss") }
$mgPath = Join-Path $mgDir ("{0}_rgsr_entitlements_prefs_drive_profiles_and_institution_apps_v1.sql" -f $MigrationId)

$sqlLines = New-Object System.Collections.Generic.List[string]

$sqlLines.Add('-- ============================================================')
$sqlLines.Add('-- RGSR: Entitlements + Preferences (C/F) + Drive Profiles + Institution Apps')
$sqlLines.Add('--      + Fix get_lab_team() + Password policy core')
$sqlLines.Add('-- ============================================================')
$sqlLines.Add('')
$sqlLines.Add('begin;')
$sqlLines.Add('')
$sqlLines.Add('create extension if not exists pgcrypto;')
$sqlLines.Add('')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('-- 0) Helper: service role detection (canonical for secure automation)')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('create or replace function rgsr.is_service_role()')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select coalesce(auth.role() = ''service_role'', false);')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('-- 1) FIX: get_lab_team() syntax error (the prior migration failed here)')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('create or replace function rgsr.get_lab_team(p_lab uuid)')
$sqlLines.Add('returns jsonb')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select jsonb_build_object(')
$sqlLines.Add('    ''lab_id'', p_lab,')
$sqlLines.Add('    ''members'', coalesce((')
$sqlLines.Add('      select jsonb_agg(')
$sqlLines.Add('        jsonb_build_object(')
$sqlLines.Add('          ''user_id'', up.user_id,')
$sqlLines.Add('          ''display_name'', up.display_name,')
$sqlLines.Add('          ''plan_id'', up.plan_id,')
$sqlLines.Add('          ''role_id'', up.role_id,')
$sqlLines.Add('          ''seat_role'', lm.seat_role,')
$sqlLines.Add('          ''is_owner'', (l.owner_id = up.user_id)')
$sqlLines.Add('        )')
$sqlLines.Add('        order by (l.owner_id = up.user_id) desc, lm.created_at asc')
$sqlLines.Add('      )')
$sqlLines.Add('      from rgsr.labs l')
$sqlLines.Add('      join rgsr.lab_members lm on lm.lab_id = l.lab_id')
$sqlLines.Add('      join rgsr.user_profiles up on up.user_id = lm.user_id')
$sqlLines.Add('      where l.lab_id = p_lab')
$sqlLines.Add('        and rgsr.is_lab_member(p_lab)')
$sqlLines.Add('        and rgsr.me_has_lab_capability(p_lab, ''TEAM_ROSTER_VIEW'')')
$sqlLines.Add('    ), ''[]''::jsonb)')
$sqlLines.Add('  );')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('-- 2) User Preferences: Celsius / Fahrenheit (profile-level setting)')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('do $$ begin')
$sqlLines.Add('  if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace')
$sqlLines.Add('                 where n.nspname=''rgsr'' and t.typname=''temp_unit'') then')
$sqlLines.Add('    create type rgsr.temp_unit as enum (''C'',''F'');')
$sqlLines.Add('  end if;')
$sqlLines.Add('end $$;')
$sqlLines.Add('')
$sqlLines.Add('create table if not exists rgsr.user_preferences (')
$sqlLines.Add('  user_id uuid primary key references auth.users(id) on delete cascade,')
$sqlLines.Add('  temp_unit rgsr.temp_unit not null default ''C'',')
$sqlLines.Add('  ui_prefs jsonb not null default ''{}''::jsonb,')
$sqlLines.Add('  created_at timestamptz not null default now(),')
$sqlLines.Add('  updated_at timestamptz not null default now()')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_trigger where tgname = ''tr_user_preferences_touch'') then')
$sqlLines.Add('    create trigger tr_user_preferences_touch')
$sqlLines.Add('    before update on rgsr.user_preferences')
$sqlLines.Add('    for each row execute function rgsr.tg_touch_updated_at();')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('alter table rgsr.user_preferences enable row level security;')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists upref_select on rgsr.user_preferences;')
$sqlLines.Add('create policy upref_select on rgsr.user_preferences for select to authenticated')
$sqlLines.Add('using (rgsr.is_sys_admin() or user_id = auth.uid());')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists upref_insert on rgsr.user_preferences;')
$sqlLines.Add('create policy upref_insert on rgsr.user_preferences for insert to authenticated')
$sqlLines.Add('with check (user_id = auth.uid());')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists upref_update on rgsr.user_preferences;')
$sqlLines.Add('create policy upref_update on rgsr.user_preferences for update to authenticated')
$sqlLines.Add('using (rgsr.is_sys_admin() or user_id = auth.uid())')
$sqlLines.Add('with check (rgsr.is_sys_admin() or user_id = auth.uid());')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.get_my_preferences()')
$sqlLines.Add('returns jsonb')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select jsonb_build_object(')
$sqlLines.Add('    ''user_id'', auth.uid(),')
$sqlLines.Add('    ''temp_unit'', coalesce((select p.temp_unit::text from rgsr.user_preferences p where p.user_id = auth.uid()), ''C''),')
$sqlLines.Add('    ''ui_prefs'', coalesce((select p.ui_prefs from rgsr.user_preferences p where p.user_id = auth.uid()), ''{}''::jsonb)')
$sqlLines.Add('  );')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.set_my_preferences(p_temp_unit text, p_ui_prefs jsonb default null)')
$sqlLines.Add('returns void')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if p_temp_unit is null or p_temp_unit not in (''C'',''F'') then')
$sqlLines.Add('    raise exception ''invalid temp unit'' using errcode = ''invalid_parameter_value'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.user_preferences(user_id, temp_unit, ui_prefs)')
$sqlLines.Add('  values (auth.uid(), p_temp_unit::rgsr.temp_unit, coalesce(p_ui_prefs, ''{}''::jsonb))')
$sqlLines.Add('  on conflict (user_id) do update')
$sqlLines.Add('    set temp_unit = excluded.temp_unit,')
$sqlLines.Add('        ui_prefs = case when p_ui_prefs is null then rgsr.user_preferences.ui_prefs else excluded.ui_prefs end,')
$sqlLines.Add('        updated_at = now();')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('revoke all on function rgsr.set_my_preferences(text, jsonb) from public;')
$sqlLines.Add('grant execute on function rgsr.get_my_preferences() to authenticated;')
$sqlLines.Add('grant execute on function rgsr.set_my_preferences(text, jsonb) to authenticated;')
$sqlLines.Add('')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('-- 3) Enriched Drive Controls: Drive Profiles (lane-aware, template-capable)')
$sqlLines.Add('--    This is the canonical, extensible model behind the screenshot controls.')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('insert into rgsr.capabilities (capability_id, description) values')
$sqlLines.Add('  (''DRIVE_PROFILE_VIEW'',      ''View drive control profiles (private + lab + published)''),')
$sqlLines.Add('  (''DRIVE_PROFILE_CREATE'',    ''Create private drive control profiles''),')
$sqlLines.Add('  (''DRIVE_PROFILE_EDIT'',      ''Edit drive profiles you own (or lab-permitted)''),')
$sqlLines.Add('  (''DRIVE_PROFILE_SHARE_LAB'', ''Share drive profiles into LAB lane''),')
$sqlLines.Add('  (''DRIVE_PROFILE_TEMPLATE'',  ''Mark drive profiles as templates''),')
$sqlLines.Add('  (''DRIVE_PROFILE_PUBLISH'',   ''Publish drive templates (PUBLISHED lane)'')')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- baseline: authenticated can view templates')
$sqlLines.Add('insert into rgsr.plan_capabilities(plan_id, capability_id, enabled) values')
$sqlLines.Add('  (''OBSERVER_FREE'',''DRIVE_PROFILE_VIEW'', true),')
$sqlLines.Add('  (''RESEARCHER_PRO'',''DRIVE_PROFILE_VIEW'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''DRIVE_PROFILE_VIEW'', true),')
$sqlLines.Add('  (''INSTITUTION'',''DRIVE_PROFILE_VIEW'', true)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- creation/edit: researcher+')
$sqlLines.Add('insert into rgsr.plan_capabilities(plan_id, capability_id, enabled) values')
$sqlLines.Add('  (''RESEARCHER_PRO'',''DRIVE_PROFILE_CREATE'', true),')
$sqlLines.Add('  (''RESEARCHER_PRO'',''DRIVE_PROFILE_EDIT'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''DRIVE_PROFILE_CREATE'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''DRIVE_PROFILE_EDIT'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''DRIVE_PROFILE_SHARE_LAB'', true),')
$sqlLines.Add('  (''INSTITUTION'',''DRIVE_PROFILE_CREATE'', true),')
$sqlLines.Add('  (''INSTITUTION'',''DRIVE_PROFILE_EDIT'', true),')
$sqlLines.Add('  (''INSTITUTION'',''DRIVE_PROFILE_SHARE_LAB'', true),')
$sqlLines.Add('  (''INSTITUTION'',''DRIVE_PROFILE_TEMPLATE'', true),')
$sqlLines.Add('  (''INSTITUTION'',''DRIVE_PROFILE_PUBLISH'', true)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('create table if not exists rgsr.drive_profiles (')
$sqlLines.Add('  drive_profile_id uuid primary key default gen_random_uuid(),')
$sqlLines.Add('  name text not null,')
$sqlLines.Add('  description text,')
$sqlLines.Add('  lane rgsr.rgsr_lane not null default ''PRIVATE'',')
$sqlLines.Add('  is_template boolean not null default false,')
$sqlLines.Add('  engine_code text not null default ''RGSR'',')
$sqlLines.Add('  owner_id uuid not null references auth.users(id) on delete cascade,')
$sqlLines.Add('  lab_id uuid references rgsr.labs(lab_id) on delete set null,')
$sqlLines.Add('  drive_json jsonb not null,')
$sqlLines.Add('  created_at timestamptz not null default now(),')
$sqlLines.Add('  updated_at timestamptz not null default now()')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_constraint where conname = ''drive_profiles_engine_name_lane_tpl_uq'') then')
$sqlLines.Add('    alter table rgsr.drive_profiles add constraint drive_profiles_engine_name_lane_tpl_uq unique (engine_code, name, lane, is_template);')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_trigger where tgname = ''tr_drive_profiles_touch'') then')
$sqlLines.Add('    create trigger tr_drive_profiles_touch')
$sqlLines.Add('    before update on rgsr.drive_profiles')
$sqlLines.Add('    for each row execute function rgsr.tg_touch_updated_at();')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.tg_drive_lane_forward_only()')
$sqlLines.Add('returns trigger language plpgsql as $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if (tg_op = ''UPDATE'') then')
$sqlLines.Add('    if rgsr.lane_rank(new.lane) < rgsr.lane_rank(old.lane) then')
$sqlLines.Add('      raise exception ''Drive profile lane is forward-only: % -> % is not allowed'', old.lane, new.lane')
$sqlLines.Add('        using errcode = ''check_violation'';')
$sqlLines.Add('    end if;')
$sqlLines.Add('  end if;')
$sqlLines.Add('  return new;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_trigger where tgname = ''tr_drive_lane_forward_only'') then')
$sqlLines.Add('    create trigger tr_drive_lane_forward_only')
$sqlLines.Add('    before update of lane on rgsr.drive_profiles')
$sqlLines.Add('    for each row execute function rgsr.tg_drive_lane_forward_only();')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.can_read_drive_profile(p_lane rgsr.rgsr_lane, p_owner uuid, p_lab uuid)')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select rgsr.is_sys_admin()')
$sqlLines.Add('  or case p_lane')
$sqlLines.Add('    when ''PUBLISHED'' then true')
$sqlLines.Add('    when ''PRIVATE'' then (auth.uid() = p_owner) and rgsr.has_capability(''DRIVE_PROFILE_VIEW'')')
$sqlLines.Add('    when ''LAB'' then (p_lab is not null and rgsr.is_lab_member(p_lab) and rgsr.has_capability(''DRIVE_PROFILE_VIEW''))')
$sqlLines.Add('    when ''REVIEW'' then (p_lab is not null and rgsr.is_lab_member(p_lab) and rgsr.has_capability(''DRIVE_PROFILE_VIEW''))')
$sqlLines.Add('  end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.can_write_drive_profile_target(p_lane rgsr.rgsr_lane, p_lab uuid)')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select rgsr.is_sys_admin()')
$sqlLines.Add('  or case p_lane')
$sqlLines.Add('    when ''PRIVATE'' then rgsr.has_capability(''DRIVE_PROFILE_CREATE'')')
$sqlLines.Add('    when ''LAB'' then (p_lab is not null and rgsr.me_has_lab_capability(p_lab, ''DRIVE_PROFILE_SHARE_LAB'') and rgsr.has_capability(''DRIVE_PROFILE_CREATE''))')
$sqlLines.Add('    when ''REVIEW'' then (p_lab is not null and rgsr.me_has_lab_capability(p_lab, ''DRIVE_PROFILE_SHARE_LAB'') and rgsr.has_capability(''DRIVE_PROFILE_CREATE''))')
$sqlLines.Add('    when ''PUBLISHED'' then rgsr.has_capability(''DRIVE_PROFILE_PUBLISH'')')
$sqlLines.Add('  end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('alter table rgsr.drive_profiles enable row level security;')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists dp_select on rgsr.drive_profiles;')
$sqlLines.Add('create policy dp_select on rgsr.drive_profiles for select to authenticated')
$sqlLines.Add('using (rgsr.can_read_drive_profile(lane, owner_id, lab_id));')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists dp_insert on rgsr.drive_profiles;')
$sqlLines.Add('create policy dp_insert on rgsr.drive_profiles for insert to authenticated')
$sqlLines.Add('with check (')
$sqlLines.Add('  owner_id = auth.uid()')
$sqlLines.Add('  and rgsr.can_write_drive_profile_target(lane, lab_id)')
$sqlLines.Add('  and (lab_id is null or rgsr.is_lab_member(lab_id))')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists dp_update on rgsr.drive_profiles;')
$sqlLines.Add('create policy dp_update on rgsr.drive_profiles for update to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or owner_id = auth.uid()')
$sqlLines.Add('  or (lab_id is not null and rgsr.me_has_lab_capability(lab_id, ''DRIVE_PROFILE_EDIT''))')
$sqlLines.Add(')')
$sqlLines.Add('with check (')
$sqlLines.Add('  rgsr.can_write_drive_profile_target(lane, lab_id)')
$sqlLines.Add('  and (lab_id is null or rgsr.is_lab_member(lab_id))')
$sqlLines.Add('  and (is_template = false or (is_template = true and rgsr.has_capability(''DRIVE_PROFILE_TEMPLATE'')))')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists dp_delete on rgsr.drive_profiles;')
$sqlLines.Add('create policy dp_delete on rgsr.drive_profiles for delete to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or owner_id = auth.uid()')
$sqlLines.Add('  or (lab_id is not null and rgsr.me_has_lab_capability(lab_id, ''DRIVE_PROFILE_EDIT''))')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- Seed a comprehensive drive template library (PUBLISHED) behind the UI controls:')
$sqlLines.Add('-- Includes waveform, modulation, sweep, pulse, ramps, safety bounds, and UI quick buttons.')
$sqlLines.Add('do $$')
$sqlLines.Add('declare seed_owner uuid;')
$sqlLines.Add('begin')
$sqlLines.Add('  seed_owner := rgsr._seed_owner_any_user();')
$sqlLines.Add('  if seed_owner is null then return; end if;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.drive_profiles(name, description, lane, is_template, engine_code, owner_id, lab_id, drive_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''RGSR Drive Baseline (440Hz)'',')
$sqlLines.Add('    ''Canonical baseline: 440Hz, sine, gentle amplitude with safety bounds.'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(')
$sqlLines.Add('      ''units'', jsonb_build_object(')
$sqlLines.Add('        ''frequency'', ''Hz'',')
$sqlLines.Add('        ''amplitude'', ''relative'',')
$sqlLines.Add('        ''temp'', ''C''')
$sqlLines.Add('      ),')
$sqlLines.Add('      ''core'', jsonb_build_object(')
$sqlLines.Add('        ''frequency_hz'', 440.0,')
$sqlLines.Add('        ''amplitude'', 0.50,')
$sqlLines.Add('        ''waveform'', ''sine'',')
$sqlLines.Add('        ''phase_deg'', 0.0')
$sqlLines.Add('      ),')
$sqlLines.Add('      ''quick_buttons'', jsonb_build_array(440, 528, 1000),')
$sqlLines.Add('      ''modulation'', jsonb_build_object(')
$sqlLines.Add('        ''enabled'', false,')
$sqlLines.Add('        ''type'', ''am'',')
$sqlLines.Add('        ''rate_hz'', 0.5,')
$sqlLines.Add('        ''depth'', 0.25,')
$sqlLines.Add('        ''fm_dev_hz'', 5.0')
$sqlLines.Add('      ),')
$sqlLines.Add('      ''sweep'', jsonb_build_object(')
$sqlLines.Add('        ''enabled'', false,')
$sqlLines.Add('        ''mode'', ''linear'',')
$sqlLines.Add('        ''start_hz'', 200.0,')
$sqlLines.Add('        ''end_hz'', 1200.0,')
$sqlLines.Add('        ''duration_s'', 60.0,')
$sqlLines.Add('        ''hold_s'', 0.0')
$sqlLines.Add('      ),')
$sqlLines.Add('      ''pulse'', jsonb_build_object(')
$sqlLines.Add('        ''enabled'', false,')
$sqlLines.Add('        ''duty_cycle'', 0.50,')
$sqlLines.Add('        ''period_s'', 2.0,')
$sqlLines.Add('        ''shape'', ''square''')
$sqlLines.Add('      ),')
$sqlLines.Add('      ''ramp'', jsonb_build_object(')
$sqlLines.Add('        ''enabled'', true,')
$sqlLines.Add('        ''attack_s'', 1.0,')
$sqlLines.Add('        ''release_s'', 1.0')
$sqlLines.Add('      ),')
$sqlLines.Add('      ''safety'', jsonb_build_object(')
$sqlLines.Add('        ''min_frequency_hz'', 0.1,')
$sqlLines.Add('        ''max_frequency_hz'', 5000.0,')
$sqlLines.Add('        ''min_amplitude'', 0.0,')
$sqlLines.Add('        ''max_amplitude'', 1.0,')
$sqlLines.Add('        ''max_rate_of_change_amp_per_s'', 0.20')
$sqlLines.Add('      ),')
$sqlLines.Add('      ''overlays'', jsonb_build_object(')
$sqlLines.Add('        ''resonance_field'', true,')
$sqlLines.Add('        ''thermal_overlay'', false,')
$sqlLines.Add('        ''acoustic_waves'', false')
$sqlLines.Add('      )')
$sqlLines.Add('    )')
$sqlLines.Add('  ) on conflict on constraint drive_profiles_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.drive_profiles(name, description, lane, is_template, engine_code, owner_id, lab_id, drive_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''RGSR Drive Sweep (200-1200Hz)'',')
$sqlLines.Add('    ''Canonical sweep profile for discovery runs: linear sweep with logging markers.'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(')
$sqlLines.Add('      ''units'', jsonb_build_object(''frequency'',''Hz'',''amplitude'',''relative''),')
$sqlLines.Add('      ''core'', jsonb_build_object(''frequency_hz'', 440.0, ''amplitude'', 0.40, ''waveform'',''sine'', ''phase_deg'', 0.0),')
$sqlLines.Add('      ''quick_buttons'', jsonb_build_array(200, 440, 1200),')
$sqlLines.Add('      ''modulation'', jsonb_build_object(''enabled'', false),')
$sqlLines.Add('      ''sweep'', jsonb_build_object(''enabled'', true, ''mode'',''linear'', ''start_hz'',200.0,''end_hz'',1200.0,''duration_s'',120.0,''hold_s'',2.0),')
$sqlLines.Add('      ''pulse'', jsonb_build_object(''enabled'', false),')
$sqlLines.Add('      ''ramp'', jsonb_build_object(''enabled'', true, ''attack_s'', 2.0, ''release_s'', 2.0),')
$sqlLines.Add('      ''safety'', jsonb_build_object(''max_frequency_hz'', 5000.0, ''max_amplitude'', 0.80),')
$sqlLines.Add('      ''markers'', jsonb_build_object(''enabled'', true, ''interval_hz'', 50.0)')
$sqlLines.Add('    )')
$sqlLines.Add('  ) on conflict on constraint drive_profiles_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('-- 4) Billing Entitlements (ROOTED-style):')
$sqlLines.Add('--    - Researcher + Lab: autoapproved (billing success -> activate immediately)')
$sqlLines.Add('--    - Institution: still uses application + admin decision + billing verify')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('create table if not exists rgsr.billing_entitlements (')
$sqlLines.Add('  entitlement_id uuid primary key default gen_random_uuid(),')
$sqlLines.Add('  provider text not null,')
$sqlLines.Add('  customer_id text not null,')
$sqlLines.Add('  subscription_id text,')
$sqlLines.Add('  user_id uuid not null references auth.users(id) on delete cascade,')
$sqlLines.Add('  plan_id rgsr.rgsr_plan_id not null,')
$sqlLines.Add('  status text not null default ''ACTIVE'',')
$sqlLines.Add('  effective_at timestamptz not null default now(),')
$sqlLines.Add('  created_at timestamptz not null default now()')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('create unique index if not exists ux_billing_entitlements_provider_customer_plan')
$sqlLines.Add('  on rgsr.billing_entitlements(provider, customer_id, plan_id);')
$sqlLines.Add('')
$sqlLines.Add('-- service-only apply entitlement (autoapproved lanes)')
$sqlLines.Add('create or replace function rgsr.apply_billing_entitlement(')
$sqlLines.Add('  p_provider text,')
$sqlLines.Add('  p_customer_id text,')
$sqlLines.Add('  p_subscription_id text,')
$sqlLines.Add('  p_user_id uuid,')
$sqlLines.Add('  p_plan_id rgsr.rgsr_plan_id')
$sqlLines.Add(') returns void')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not (rgsr.is_sys_admin() or rgsr.is_service_role()) then')
$sqlLines.Add('    raise exception ''not authorized'' using errcode = ''insufficient_privilege'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.billing_entitlements(provider, customer_id, subscription_id, user_id, plan_id, status)')
$sqlLines.Add('  values (p_provider, p_customer_id, p_subscription_id, p_user_id, p_plan_id, ''ACTIVE'')')
$sqlLines.Add('  on conflict (provider, customer_id, plan_id) do update')
$sqlLines.Add('    set subscription_id = excluded.subscription_id,')
$sqlLines.Add('        user_id = excluded.user_id,')
$sqlLines.Add('        status = ''ACTIVE'',')
$sqlLines.Add('        effective_at = now();')
$sqlLines.Add('')
$sqlLines.Add('  -- Apply plan to profile (autoapproved: RESEARCHER_PRO / LAB_STANDARD only)')
$sqlLines.Add('  if p_plan_id in (''RESEARCHER_PRO''::rgsr.rgsr_plan_id, ''LAB_STANDARD''::rgsr.rgsr_plan_id) then')
$sqlLines.Add('    update rgsr.user_profiles set plan_id = p_plan_id where user_id = p_user_id;')
$sqlLines.Add('  end if;')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('revoke all on function rgsr.apply_billing_entitlement(text, text, text, uuid, rgsr.rgsr_plan_id) from public;')
$sqlLines.Add('grant execute on function rgsr.apply_billing_entitlement(text, text, text, uuid, rgsr.rgsr_plan_id) to authenticated;')
$sqlLines.Add('')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('-- 5) Institution Applications (admin review + billing verify -> activate)')
$sqlLines.Add('--    (If your institution table already exists from earlier work, this is additive-safe.)')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('do $$ begin')
$sqlLines.Add('  if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace')
$sqlLines.Add('                 where n.nspname=''rgsr'' and t.typname=''institution_application_status'') then')
$sqlLines.Add('    create type rgsr.institution_application_status as enum (')
$sqlLines.Add('      ''DRAFT'', ''SUBMITTED'', ''APPROVED_PENDING_PAYMENT'', ''REJECTED'', ''ACTIVE''')
$sqlLines.Add('    );')
$sqlLines.Add('  end if;')
$sqlLines.Add('end $$;')
$sqlLines.Add('')
$sqlLines.Add('create table if not exists rgsr.institution_access_applications (')
$sqlLines.Add('  application_id uuid primary key default gen_random_uuid(),')
$sqlLines.Add('  applicant_user_id uuid not null references auth.users(id) on delete cascade,')
$sqlLines.Add('  applicant_email text,')
$sqlLines.Add('  org_name text not null,')
$sqlLines.Add('  org_type text,')
$sqlLines.Add('  website text,')
$sqlLines.Add('  country_code text,')
$sqlLines.Add('  contact_name text,')
$sqlLines.Add('  contact_phone text,')
$sqlLines.Add('  requested_seats integer not null default 1 check (requested_seats between 1 and 1000),')
$sqlLines.Add('  requested_plan_id rgsr.rgsr_plan_id not null default ''INSTITUTION''::rgsr.rgsr_plan_id,')
$sqlLines.Add('  notes text,')
$sqlLines.Add('  status rgsr.institution_application_status not null default ''DRAFT'',')
$sqlLines.Add('  submitted_at timestamptz,')
$sqlLines.Add('  reviewed_by uuid references auth.users(id) on delete set null,')
$sqlLines.Add('  reviewed_at timestamptz,')
$sqlLines.Add('  decision_reason text,')
$sqlLines.Add('  billing_provider text,')
$sqlLines.Add('  billing_customer_id text,')
$sqlLines.Add('  billing_subscription_id text,')
$sqlLines.Add('  billing_verified_at timestamptz,')
$sqlLines.Add('  activated_at timestamptz,')
$sqlLines.Add('  created_at timestamptz not null default now(),')
$sqlLines.Add('  updated_at timestamptz not null default now()')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('create index if not exists ix_inst_apps_applicant on rgsr.institution_access_applications(applicant_user_id, created_at desc);')
$sqlLines.Add('create index if not exists ix_inst_apps_status on rgsr.institution_access_applications(status, created_at desc);')
$sqlLines.Add('')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_trigger where tgname = ''tr_inst_apps_touch'') then')
$sqlLines.Add('    create trigger tr_inst_apps_touch')
$sqlLines.Add('    before update on rgsr.institution_access_applications')
$sqlLines.Add('    for each row execute function rgsr.tg_touch_updated_at();')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('insert into rgsr.capabilities (capability_id, description) values')
$sqlLines.Add('  (''INSTITUTION_APPLY'', ''Submit an institutional access application''),')
$sqlLines.Add('  (''INSTITUTION_APP_TRACK'', ''View your institutional application tracker/dashboard''),')
$sqlLines.Add('  (''INSTITUTION_APP_REVIEW'', ''Admin can review/approve/reject institutional applications''),')
$sqlLines.Add('  (''INSTITUTION_BILLING_VERIFY'', ''Admin/system can mark billing verified and activate entitlements'')')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('insert into rgsr.plan_capabilities(plan_id, capability_id, enabled) values')
$sqlLines.Add('  (''OBSERVER_FREE'',''INSTITUTION_APPLY'', true),')
$sqlLines.Add('  (''OBSERVER_FREE'',''INSTITUTION_APP_TRACK'', true),')
$sqlLines.Add('  (''RESEARCHER_PRO'',''INSTITUTION_APPLY'', true),')
$sqlLines.Add('  (''RESEARCHER_PRO'',''INSTITUTION_APP_TRACK'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''INSTITUTION_APPLY'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''INSTITUTION_APP_TRACK'', true),')
$sqlLines.Add('  (''INSTITUTION'',''INSTITUTION_APP_TRACK'', true)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('alter table rgsr.institution_access_applications enable row level security;')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists inst_app_select on rgsr.institution_access_applications;')
$sqlLines.Add('create policy inst_app_select on rgsr.institution_access_applications for select to authenticated')
$sqlLines.Add('using (rgsr.is_sys_admin() or applicant_user_id = auth.uid());')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists inst_app_insert on rgsr.institution_access_applications;')
$sqlLines.Add('create policy inst_app_insert on rgsr.institution_access_applications for insert to authenticated')
$sqlLines.Add('with check (applicant_user_id = auth.uid() and rgsr.has_capability(''INSTITUTION_APPLY''));')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists inst_app_update on rgsr.institution_access_applications;')
$sqlLines.Add('create policy inst_app_update on rgsr.institution_access_applications for update to authenticated')
$sqlLines.Add('using (rgsr.is_sys_admin() or applicant_user_id = auth.uid())')
$sqlLines.Add('with check (rgsr.is_sys_admin() or (applicant_user_id = auth.uid() and status in (''DRAFT'',''SUBMITTED'')));')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.submit_institution_application(p_org_name text, p_requested_seats integer, p_payload jsonb default ''{}''::jsonb)')
$sqlLines.Add('returns uuid')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('declare app_id uuid;')
$sqlLines.Add('begin')
$sqlLines.Add('  if not rgsr.has_capability(''INSTITUTION_APPLY'') then')
$sqlLines.Add('    raise exception ''not authorized'' using errcode = ''insufficient_privilege'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('  insert into rgsr.institution_access_applications(')
$sqlLines.Add('    applicant_user_id, applicant_email, org_name, requested_seats, org_type, website, country_code, contact_name, contact_phone, notes, status, submitted_at, requested_plan_id')
$sqlLines.Add('  ) values (')
$sqlLines.Add('    auth.uid(), (select email from auth.users where id = auth.uid()), p_org_name, p_requested_seats,')
$sqlLines.Add('    nullif(p_payload->>''org_type'',''''), nullif(p_payload->>''website'',''''), nullif(p_payload->>''country_code'',''''),')
$sqlLines.Add('    nullif(p_payload->>''contact_name'',''''), nullif(p_payload->>''contact_phone'',''''), nullif(p_payload->>''notes'',''''),')
$sqlLines.Add('    ''SUBMITTED'', now(), ''INSTITUTION''::rgsr.rgsr_plan_id')
$sqlLines.Add('  ) returning application_id into app_id;')
$sqlLines.Add('  return app_id;')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.get_my_institution_applications()')
$sqlLines.Add('returns jsonb')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select jsonb_build_object(')
$sqlLines.Add('    ''applications'', coalesce((')
$sqlLines.Add('      select jsonb_agg(jsonb_build_object(')
$sqlLines.Add('        ''application_id'', a.application_id,')
$sqlLines.Add('        ''org_name'', a.org_name,')
$sqlLines.Add('        ''requested_seats'', a.requested_seats,')
$sqlLines.Add('        ''status'', a.status::text,')
$sqlLines.Add('        ''submitted_at'', a.submitted_at,')
$sqlLines.Add('        ''reviewed_at'', a.reviewed_at,')
$sqlLines.Add('        ''decision_reason'', a.decision_reason,')
$sqlLines.Add('        ''billing_verified_at'', a.billing_verified_at,')
$sqlLines.Add('        ''activated_at'', a.activated_at,')
$sqlLines.Add('        ''created_at'', a.created_at')
$sqlLines.Add('      ) order by a.created_at desc)')
$sqlLines.Add('      from rgsr.institution_access_applications a')
$sqlLines.Add('      where a.applicant_user_id = auth.uid()')
$sqlLines.Add('    ), ''[]''::jsonb)')
$sqlLines.Add('  );')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.admin_review_institution_application(p_application_id uuid, p_decision text, p_reason text default null)')
$sqlLines.Add('returns void')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not rgsr.is_sys_admin() then')
$sqlLines.Add('    raise exception ''not authorized'' using errcode = ''insufficient_privilege'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('  if p_decision not in (''APPROVE'',''REJECT'') then')
$sqlLines.Add('    raise exception ''invalid decision'' using errcode = ''invalid_parameter_value'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('  update rgsr.institution_access_applications')
$sqlLines.Add('  set status = case when p_decision = ''APPROVE'' then ''APPROVED_PENDING_PAYMENT'' else ''REJECTED'' end,')
$sqlLines.Add('      reviewed_by = auth.uid(),')
$sqlLines.Add('      reviewed_at = now(),')
$sqlLines.Add('      decision_reason = p_reason')
$sqlLines.Add('  where application_id = p_application_id')
$sqlLines.Add('    and status = ''SUBMITTED'';')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.admin_verify_institution_billing_and_activate(p_application_id uuid, p_provider text, p_customer_id text, p_subscription_id text)')
$sqlLines.Add('returns void')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('declare uid uuid;')
$sqlLines.Add('begin')
$sqlLines.Add('  if not (rgsr.is_sys_admin() or rgsr.is_service_role()) then')
$sqlLines.Add('    raise exception ''not authorized'' using errcode = ''insufficient_privilege'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('  select a.applicant_user_id into uid')
$sqlLines.Add('  from rgsr.institution_access_applications a')
$sqlLines.Add('  where a.application_id = p_application_id')
$sqlLines.Add('    and a.status = ''APPROVED_PENDING_PAYMENT'';')
$sqlLines.Add('  if uid is null then')
$sqlLines.Add('    raise exception ''application not eligible for activation'' using errcode = ''check_violation'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('  update rgsr.institution_access_applications')
$sqlLines.Add('  set billing_provider = p_provider,')
$sqlLines.Add('      billing_customer_id = p_customer_id,')
$sqlLines.Add('      billing_subscription_id = p_subscription_id,')
$sqlLines.Add('      billing_verified_at = now(),')
$sqlLines.Add('      status = ''ACTIVE'',')
$sqlLines.Add('      activated_at = now()')
$sqlLines.Add('  where application_id = p_application_id;')
$sqlLines.Add('  update rgsr.user_profiles set plan_id = ''INSTITUTION''::rgsr.rgsr_plan_id where user_id = uid;')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('revoke all on function rgsr.submit_institution_application(text, integer, jsonb) from public;')
$sqlLines.Add('revoke all on function rgsr.admin_review_institution_application(uuid, text, text) from public;')
$sqlLines.Add('revoke all on function rgsr.admin_verify_institution_billing_and_activate(uuid, text, text, text) from public;')
$sqlLines.Add('grant execute on function rgsr.submit_institution_application(text, integer, jsonb) to authenticated;')
$sqlLines.Add('grant execute on function rgsr.get_my_institution_applications() to authenticated;')
$sqlLines.Add('grant execute on function rgsr.admin_review_institution_application(uuid, text, text) to authenticated;')
$sqlLines.Add('grant execute on function rgsr.admin_verify_institution_billing_and_activate(uuid, text, text, text) to authenticated;')
$sqlLines.Add('')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('-- 6) Password Policy Core (ROOTED-style): rotation + history')
$sqlLines.Add('--    DB side is canonical source of truth; enforcement is done via service-role hook/RPC.')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('create table if not exists rgsr.password_policy (')
$sqlLines.Add('  policy_id text primary key default ''DEFAULT'',')
$sqlLines.Add('  min_length int not null default 14,')
$sqlLines.Add('  require_upper boolean not null default true,')
$sqlLines.Add('  require_lower boolean not null default true,')
$sqlLines.Add('  require_number boolean not null default true,')
$sqlLines.Add('  require_symbol boolean not null default true,')
$sqlLines.Add('  history_count int not null default 12,')
$sqlLines.Add('  rotate_days int not null default 90,')
$sqlLines.Add('  created_at timestamptz not null default now()')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('insert into rgsr.password_policy(policy_id) values (''DEFAULT'') on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('create table if not exists rgsr.password_history (')
$sqlLines.Add('  user_id uuid not null references auth.users(id) on delete cascade,')
$sqlLines.Add('  password_hash text not null,')
$sqlLines.Add('  created_at timestamptz not null default now()')
$sqlLines.Add(');')
$sqlLines.Add('create index if not exists ix_password_history_user_time on rgsr.password_history(user_id, created_at desc);')
$sqlLines.Add('')
$sqlLines.Add('create table if not exists rgsr.password_rotation (')
$sqlLines.Add('  user_id uuid primary key references auth.users(id) on delete cascade,')
$sqlLines.Add('  last_changed_at timestamptz not null default now(),')
$sqlLines.Add('  next_required_at timestamptz not null default (now() + interval ''90 days'')')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr._password_meets_policy(p_password text)')
$sqlLines.Add('returns boolean language plpgsql stable as $$')
$sqlLines.Add('declare pol record;')
$sqlLines.Add('begin')
$sqlLines.Add('  select * into pol from rgsr.password_policy where policy_id = ''DEFAULT'';')
$sqlLines.Add('  if p_password is null or length(p_password) < pol.min_length then return false; end if;')
$sqlLines.Add('  if pol.require_upper and p_password !~ ''[A-Z]'' then return false; end if;')
$sqlLines.Add('  if pol.require_lower and p_password !~ ''[a-z]'' then return false; end if;')
$sqlLines.Add('  if pol.require_number and p_password !~ ''[0-9]'' then return false; end if;')
$sqlLines.Add('  if pol.require_symbol and p_password !~ ''[^A-Za-z0-9]'' then return false; end if;')
$sqlLines.Add('  return true;')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr._password_is_reused(p_user uuid, p_password text)')
$sqlLines.Add('returns boolean language sql stable as $$')
$sqlLines.Add('  select exists (')
$sqlLines.Add('    select 1 from rgsr.password_history h')
$sqlLines.Add('    where h.user_id = p_user')
$sqlLines.Add('      and h.password_hash = crypt(p_password, h.password_hash)')
$sqlLines.Add('  );')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.service_record_password_change(p_user uuid, p_new_password text)')
$sqlLines.Add('returns void')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('declare pol record;')
$sqlLines.Add('begin')
$sqlLines.Add('  if not (rgsr.is_sys_admin() or rgsr.is_service_role()) then')
$sqlLines.Add('    raise exception ''not authorized'' using errcode = ''insufficient_privilege'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('  if not rgsr._password_meets_policy(p_new_password) then')
$sqlLines.Add('    raise exception ''password does not meet policy'' using errcode = ''invalid_parameter_value'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('  if rgsr._password_is_reused(p_user, p_new_password) then')
$sqlLines.Add('    raise exception ''password reuse not allowed'' using errcode = ''invalid_parameter_value'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('  select * into pol from rgsr.password_policy where policy_id = ''DEFAULT'';')
$sqlLines.Add('  insert into rgsr.password_history(user_id, password_hash)')
$sqlLines.Add('  values (p_user, crypt(p_new_password, gen_salt(''bf''))) ;')
$sqlLines.Add('  delete from rgsr.password_history')
$sqlLines.Add('  where user_id = p_user')
$sqlLines.Add('    and ctid in (')
$sqlLines.Add('      select ctid from rgsr.password_history')
$sqlLines.Add('      where user_id = p_user')
$sqlLines.Add('      order by created_at desc')
$sqlLines.Add('      offset pol.history_count')
$sqlLines.Add('    );')
$sqlLines.Add('  insert into rgsr.password_rotation(user_id, last_changed_at, next_required_at)')
$sqlLines.Add('  values (p_user, now(), now() + (pol.rotate_days || '' days'')::interval)')
$sqlLines.Add('  on conflict (user_id) do update')
$sqlLines.Add('    set last_changed_at = now(), next_required_at = now() + (pol.rotate_days || '' days'')::interval;')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('revoke all on function rgsr.service_record_password_change(uuid, text) from public;')
$sqlLines.Add('grant execute on function rgsr.service_record_password_change(uuid, text) to authenticated;')
$sqlLines.Add('')
$sqlLines.Add('commit;')
$sqlLines.Add('')
$sqlLines.Add('-- ============================================================')
$sqlLines.Add('-- End migration')
$sqlLines.Add('-- ============================================================')

$sql = ($sqlLines -join "`r`n") + "`r`n"
WriteUtf8NoBomIfChanged $mgPath $sql
Write-Host ("[OK] MIGRATION READY: " + $mgPath) -ForegroundColor Green

if ($LinkProject) {
  if (-not $ProjectRef) { throw "ProjectRef is required for link." }
  supabase link --project-ref $ProjectRef
}

if ($ApplyRemote) {
  supabase db push
}

Write-Host "✅ RGSR ENTITLEMENTS + PREFS + DRIVE PROFILES + INSTITUTION APPS PIPELINE COMPLETE" -ForegroundColor Green
