param(
  [Parameter(Mandatory)][string]$RepoRoot,
  [string]$MigrationId = "",
  [switch]$LinkProject,
  [string]$ProjectRef = "",
  [switch]$ApplyRemote
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function EnsureDir([string]$p) { if (-not (Test-Path -LiteralPath $p)) { New-Item -ItemType Directory -Path $p -Force | Out-Null } }
function WriteUtf8NoBomIfChanged([string]$Path, [string]$Content) {
  $dir = Split-Path -Parent $Path
  if ($dir) { EnsureDir $dir }
  $enc = New-Object System.Text.UTF8Encoding($false)
  $existing = $null
  if (Test-Path -LiteralPath $Path) { $existing = Get-Content -Raw -LiteralPath $Path -Encoding UTF8 }
  if ($existing -ne $Content) {
    [IO.File]::WriteAllText($Path, $Content, $enc)
    Write-Host ("[OK] WROTE " + $Path) -ForegroundColor DarkGreen
  } else {
    Write-Host ("[OK] NO-CHANGE " + $Path) -ForegroundColor DarkCyan
  }
}

if (-not (Test-Path -LiteralPath $RepoRoot)) { throw "RepoRoot not found: $RepoRoot" }
Set-Location $RepoRoot

$mgDir = Join-Path $RepoRoot "supabase\migrations"
EnsureDir $mgDir

if (-not $MigrationId) { $MigrationId = (Get-Date).ToUniversalTime().ToString("yyyyMMddHHmmss") }
$mgPath = Join-Path $mgDir ("{0}_rgsr_team_seats_invites_v1.sql" -f $MigrationId)

# SQL body as lines -> joined (no quoting traps)
$sqlLines = New-Object System.Collections.Generic.List[string]

$sqlLines.Add('-- ============================================================')
$sqlLines.Add('-- RGSR: Team Seats + Invites + Private Team Management (V1)')
$sqlLines.Add('-- Canonical: per-lab roles ("seats"), invite workflow, RLS locked')
$sqlLines.Add('-- No public team data; lab membership is private to that lab.')
$sqlLines.Add('-- ============================================================')
$sqlLines.Add('')
$sqlLines.Add('begin;')
$sqlLines.Add('')
$sqlLines.Add('create extension if not exists pgcrypto;')
$sqlLines.Add('')
$sqlLines.Add('-- 1) Enums')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_type where typname = ''rgsr_lab_role'') then')
$sqlLines.Add('    create type rgsr.rgsr_lab_role as enum (''OWNER'',''ADMIN'',''MEMBER'',''VIEWER'');')
$sqlLines.Add('  end if;')
$sqlLines.Add('')
$sqlLines.Add('  if not exists (select 1 from pg_type where typname = ''rgsr_invite_status'') then')
$sqlLines.Add('    create type rgsr.rgsr_invite_status as enum (''PENDING'',''ACCEPTED'',''REVOKED'',''EXPIRED'');')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- 2) Capabilities (team + profile)')
$sqlLines.Add('insert into rgsr.capabilities (capability_id, description) values')
$sqlLines.Add('  (''PROFILE_EDIT'',        ''Edit your own profile''),')
$sqlLines.Add('  (''TEAM_VIEW'',           ''View lab team roster (private to lab)''),')
$sqlLines.Add('  (''TEAM_INVITE'',         ''Invite members to your lab''),')
$sqlLines.Add('  (''TEAM_MANAGE'',         ''Manage lab seats/roles/remove members''),')
$sqlLines.Add('  (''LAB_EDIT'',            ''Edit lab metadata/settings'' )')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- 3) Lab role -> capabilities (seat capabilities)')
$sqlLines.Add('create table if not exists rgsr.lab_role_capabilities (')
$sqlLines.Add('  lab_role      rgsr.rgsr_lab_role not null,')
$sqlLines.Add('  capability_id text not null references rgsr.capabilities(capability_id) on delete cascade,')
$sqlLines.Add('  enabled       boolean not null default true,')
$sqlLines.Add('  primary key (lab_role, capability_id)')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- Seed: VIEWER can only TEAM_VIEW; MEMBER can TEAM_VIEW; ADMIN can TEAM_*; OWNER full team + lab edit')
$sqlLines.Add('insert into rgsr.lab_role_capabilities (lab_role, capability_id, enabled) values')
$sqlLines.Add('  (''VIEWER'',''TEAM_VIEW'', true),')
$sqlLines.Add('  (''MEMBER'',''TEAM_VIEW'', true),')
$sqlLines.Add('  (''ADMIN'',''TEAM_VIEW'', true),')
$sqlLines.Add('  (''ADMIN'',''TEAM_INVITE'', true),')
$sqlLines.Add('  (''ADMIN'',''TEAM_MANAGE'', true),')
$sqlLines.Add('  (''OWNER'',''TEAM_VIEW'', true),')
$sqlLines.Add('  (''OWNER'',''TEAM_INVITE'', true),')
$sqlLines.Add('  (''OWNER'',''TEAM_MANAGE'', true),')
$sqlLines.Add('  (''OWNER'',''LAB_EDIT'', true)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- 4) Ensure user_profiles supports self-edit (capability-based)')
$sqlLines.Add('-- If you want PROFILE_EDIT by plan/role, seed it here for all authenticated plans:')
$sqlLines.Add('insert into rgsr.plan_capabilities(plan_id, capability_id, enabled)')
$sqlLines.Add('select p.plan_id, ''PROFILE_EDIT'', true')
$sqlLines.Add('from (values')
$sqlLines.Add('  (''OBSERVER_FREE''::rgsr.rgsr_plan_id),')
$sqlLines.Add('  (''RESEARCHER_PRO''::rgsr.rgsr_plan_id),')
$sqlLines.Add('  (''LAB_STANDARD''::rgsr.rgsr_plan_id),')
$sqlLines.Add('  (''INSTITUTION''::rgsr.rgsr_plan_id)')
$sqlLines.Add(') as p(plan_id)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- 5) Upgrade lab_members into true "seats": add seat_role + make it canonical')
$sqlLines.Add('alter table rgsr.lab_members add column if not exists seat_role rgsr.rgsr_lab_role;')
$sqlLines.Add('')
$sqlLines.Add('-- Backfill seat_role from existing is_admin / ownership (safe idempotent)')
$sqlLines.Add('update rgsr.lab_members lm')
$sqlLines.Add('set seat_role = case')
$sqlLines.Add('  when lm.seat_role is not null then lm.seat_role')
$sqlLines.Add('  when lm.is_admin is true then ''ADMIN''::rgsr.rgsr_lab_role')
$sqlLines.Add('  else ''MEMBER''::rgsr.rgsr_lab_role')
$sqlLines.Add('end')
$sqlLines.Add('where lm.seat_role is null;')
$sqlLines.Add('')
$sqlLines.Add('-- Ensure lab owner always has OWNER seat (creates if missing)')
$sqlLines.Add('insert into rgsr.lab_members (lab_id, user_id, is_admin, created_at, seat_role)')
$sqlLines.Add('select l.lab_id, l.owner_id, true, now(), ''OWNER''::rgsr.rgsr_lab_role')
$sqlLines.Add('from rgsr.labs l')
$sqlLines.Add('where not exists (')
$sqlLines.Add('  select 1 from rgsr.lab_members lm')
$sqlLines.Add('  where lm.lab_id = l.lab_id and lm.user_id = l.owner_id')
$sqlLines.Add(')')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- Enforce NOT NULL after backfill (safe)')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if exists (select 1 from information_schema.columns')
$sqlLines.Add('             where table_schema = ''rgsr'' and table_name = ''lab_members'' and column_name = ''seat_role''')
$sqlLines.Add('               and is_nullable = ''YES'') then')
$sqlLines.Add('    -- Only set NOT NULL if no nulls remain')
$sqlLines.Add('    if not exists (select 1 from rgsr.lab_members where seat_role is null) then')
$sqlLines.Add('      alter table rgsr.lab_members alter column seat_role set not null;')
$sqlLines.Add('    end if;')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- 6) Seat capability checks (per lab)')
$sqlLines.Add('create or replace function rgsr.current_lab_role(p_lab uuid)')
$sqlLines.Add('returns rgsr.rgsr_lab_role')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select')
$sqlLines.Add('    case')
$sqlLines.Add('      when exists (select 1 from rgsr.labs l where l.lab_id = p_lab and l.owner_id = auth.uid()) then ''OWNER''::rgsr.rgsr_lab_role')
$sqlLines.Add('      else coalesce((select lm.seat_role from rgsr.lab_members lm where lm.lab_id = p_lab and lm.user_id = auth.uid()), ''VIEWER''::rgsr.rgsr_lab_role)')
$sqlLines.Add('    end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.has_lab_capability(p_lab uuid, p_cap text)')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select rgsr.is_sys_admin()')
$sqlLines.Add('  or exists (')
$sqlLines.Add('    select 1')
$sqlLines.Add('    from rgsr.lab_role_capabilities lrc')
$sqlLines.Add('    where lrc.lab_role = rgsr.current_lab_role(p_lab)')
$sqlLines.Add('      and lrc.capability_id = p_cap')
$sqlLines.Add('      and lrc.enabled')
$sqlLines.Add('  );')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.can_manage_lab(p_lab uuid)')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select rgsr.has_lab_capability(p_lab, ''TEAM_MANAGE'')')
$sqlLines.Add('      or rgsr.has_lab_capability(p_lab, ''LAB_EDIT'');')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('-- 7) Lab invites (private to lab admins/owner)')
$sqlLines.Add('create table if not exists rgsr.lab_invites (')
$sqlLines.Add('  invite_id      uuid primary key default gen_random_uuid(),')
$sqlLines.Add('  lab_id         uuid not null references rgsr.labs(lab_id) on delete cascade,')
$sqlLines.Add('  email          text not null,')
$sqlLines.Add('  seat_role      rgsr.rgsr_lab_role not null default ''MEMBER'',')
$sqlLines.Add('  status         rgsr.rgsr_invite_status not null default ''PENDING'',')
$sqlLines.Add('  token_sha256   text not null,')
$sqlLines.Add('  created_by     uuid not null references auth.users(id) on delete cascade,')
$sqlLines.Add('  created_at     timestamptz not null default now(),')
$sqlLines.Add('  expires_at     timestamptz not null default (now() + interval ''7 days''),')
$sqlLines.Add('  accepted_at    timestamptz,')
$sqlLines.Add('  accepted_by    uuid references auth.users(id) on delete set null,')
$sqlLines.Add('  revoked_at     timestamptz,')
$sqlLines.Add('  unique(lab_id, email, status)')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('create index if not exists idx_lab_invites_lab_id on rgsr.lab_invites(lab_id);')
$sqlLines.Add('create index if not exists idx_lab_invites_token_sha on rgsr.lab_invites(token_sha256);')
$sqlLines.Add('')
$sqlLines.Add('-- 8) Invite RPCs (canonical one-shot, no exposing token hash)')
$sqlLines.Add('create or replace function rgsr.create_lab_invite(p_lab uuid, p_email text, p_seat_role rgsr.rgsr_lab_role default ''MEMBER'')')
$sqlLines.Add('returns table(invite_id uuid, invite_token text, expires_at timestamptz)')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('declare')
$sqlLines.Add('  raw_token text;')
$sqlLines.Add('  token_hash text;')
$sqlLines.Add('  out_id uuid;')
$sqlLines.Add('  out_exp timestamptz;')
$sqlLines.Add('begin')
$sqlLines.Add('  if p_email is null or length(trim(p_email)) = 0 then')
$sqlLines.Add('    raise exception ''email is required'' using errcode = ''invalid_parameter_value'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('')
$sqlLines.Add('  if not rgsr.has_lab_capability(p_lab, ''TEAM_INVITE'') then')
$sqlLines.Add('    raise exception ''not authorized to invite'' using errcode = ''insufficient_privilege'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('')
$sqlLines.Add('  -- token: 32 bytes random -> hex')
$sqlLines.Add('  raw_token := encode(gen_random_bytes(32), ''hex'');')
$sqlLines.Add('  token_hash := encode(digest(raw_token, ''sha256''), ''hex'');')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.lab_invites(lab_id, email, seat_role, status, token_sha256, created_by, expires_at)')
$sqlLines.Add('  values (p_lab, lower(trim(p_email)), p_seat_role, ''PENDING'', token_hash, auth.uid(), now() + interval ''7 days'')')
$sqlLines.Add('  returning rgsr.lab_invites.invite_id, rgsr.lab_invites.expires_at into out_id, out_exp;')
$sqlLines.Add('')
$sqlLines.Add('  return query select out_id, raw_token, out_exp;')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.accept_lab_invite(p_token text)')
$sqlLines.Add('returns table(lab_id uuid, seat_role rgsr.rgsr_lab_role)')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('declare')
$sqlLines.Add('  token_hash text;')
$sqlLines.Add('  inv record;')
$sqlLines.Add('begin')
$sqlLines.Add('  if p_token is null or length(trim(p_token)) = 0 then')
$sqlLines.Add('    raise exception ''token is required'' using errcode = ''invalid_parameter_value'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('')
$sqlLines.Add('  token_hash := encode(digest(p_token, ''sha256''), ''hex'');')
$sqlLines.Add('')
$sqlLines.Add('  select * into inv')
$sqlLines.Add('  from rgsr.lab_invites li')
$sqlLines.Add('  where li.token_sha256 = token_hash')
$sqlLines.Add('    and li.status = ''PENDING''')
$sqlLines.Add('  limit 1;')
$sqlLines.Add('')
$sqlLines.Add('  if not found then')
$sqlLines.Add('    raise exception ''invite not found or not pending'' using errcode = ''invalid_parameter_value'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('')
$sqlLines.Add('  if inv.expires_at < now() then')
$sqlLines.Add('    update rgsr.lab_invites set status = ''EXPIRED'' where invite_id = inv.invite_id;')
$sqlLines.Add('    raise exception ''invite expired'' using errcode = ''invalid_parameter_value'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('')
$sqlLines.Add('  -- attach seat')
$sqlLines.Add('  insert into rgsr.lab_members(lab_id, user_id, is_admin, created_at, seat_role)')
$sqlLines.Add('  values (inv.lab_id, auth.uid(), (inv.seat_role in (''OWNER'',''ADMIN'')), now(), inv.seat_role)')
$sqlLines.Add('  on conflict (lab_id, user_id) do update')
$sqlLines.Add('    set seat_role = excluded.seat_role,')
$sqlLines.Add('        is_admin = excluded.is_admin;')
$sqlLines.Add('')
$sqlLines.Add('  update rgsr.lab_invites')
$sqlLines.Add('  set status = ''ACCEPTED'', accepted_at = now(), accepted_by = auth.uid()')
$sqlLines.Add('  where invite_id = inv.invite_id;')
$sqlLines.Add('')
$sqlLines.Add('  return query select inv.lab_id, inv.seat_role;')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.revoke_lab_invite(p_invite_id uuid)')
$sqlLines.Add('returns void')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('declare')
$sqlLines.Add('  inv record;')
$sqlLines.Add('begin')
$sqlLines.Add('  select * into inv from rgsr.lab_invites where invite_id = p_invite_id;')
$sqlLines.Add('  if not found then')
$sqlLines.Add('    return;')
$sqlLines.Add('  end if;')
$sqlLines.Add('')
$sqlLines.Add('  if not rgsr.has_lab_capability(inv.lab_id, ''TEAM_INVITE'') then')
$sqlLines.Add('    raise exception ''not authorized to revoke'' using errcode = ''insufficient_privilege'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('')
$sqlLines.Add('  update rgsr.lab_invites')
$sqlLines.Add('  set status = ''REVOKED'', revoked_at = now()')
$sqlLines.Add('  where invite_id = p_invite_id and status = ''PENDING'';')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('-- 9) Private "my profile" view for UI Profile menu')
$sqlLines.Add('create or replace view rgsr.v_my_profile as')
$sqlLines.Add('select')
$sqlLines.Add('  up.user_id,')
$sqlLines.Add('  up.display_name,')
$sqlLines.Add('  up.role_id,')
$sqlLines.Add('  up.plan_id,')
$sqlLines.Add('  (')
$sqlLines.Add('    select coalesce(jsonb_agg(jsonb_build_object(')
$sqlLines.Add('      ''lab_id'', l.lab_id,')
$sqlLines.Add('      ''name'', l.name,')
$sqlLines.Add('      ''seat_role'', rgsr.current_lab_role(l.lab_id)')
$sqlLines.Add('    ) order by l.created_at), ''[]''::jsonb)')
$sqlLines.Add('    from rgsr.labs l')
$sqlLines.Add('    where exists (')
$sqlLines.Add('      select 1 from rgsr.lab_members lm')
$sqlLines.Add('      where lm.lab_id = l.lab_id and lm.user_id = auth.uid()')
$sqlLines.Add('    ) or l.owner_id = auth.uid()')
$sqlLines.Add('  ) as labs')
$sqlLines.Add('from rgsr.user_profiles up')
$sqlLines.Add('where up.user_id = auth.uid();')
$sqlLines.Add('')
$sqlLines.Add('-- 10) RLS: lock team data to the lab')
$sqlLines.Add('alter table rgsr.lab_invites enable row level security;')
$sqlLines.Add('')
$sqlLines.Add('-- lab_members: allow only members of that lab to see roster (private), and only admins/owner to modify')
$sqlLines.Add('drop policy if exists lm_select on rgsr.lab_members;')
$sqlLines.Add('create policy lm_select on rgsr.lab_members for select to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or rgsr.is_lab_member(lab_id)')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists lm_insert on rgsr.lab_members;')
$sqlLines.Add('create policy lm_insert on rgsr.lab_members for insert to authenticated')
$sqlLines.Add('with check (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or rgsr.has_lab_capability(lab_id, ''TEAM_MANAGE'')')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists lm_update on rgsr.lab_members;')
$sqlLines.Add('create policy lm_update on rgsr.lab_members for update to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or rgsr.has_lab_capability(lab_id, ''TEAM_MANAGE'')')
$sqlLines.Add(')')
$sqlLines.Add('with check (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or rgsr.has_lab_capability(lab_id, ''TEAM_MANAGE'')')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists lm_delete on rgsr.lab_members;')
$sqlLines.Add('create policy lm_delete on rgsr.lab_members for delete to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or rgsr.has_lab_capability(lab_id, ''TEAM_MANAGE'')')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- labs: members can see their lab; only OWNER/ADMIN can edit lab metadata')
$sqlLines.Add('drop policy if exists labs_select on rgsr.labs;')
$sqlLines.Add('create policy labs_select on rgsr.labs for select to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or owner_id = auth.uid()')
$sqlLines.Add('  or exists (select 1 from rgsr.lab_members lm where lm.lab_id = labs.lab_id and lm.user_id = auth.uid())')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists labs_update on rgsr.labs;')
$sqlLines.Add('create policy labs_update on rgsr.labs for update to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or owner_id = auth.uid()')
$sqlLines.Add('  or rgsr.has_lab_capability(labs.lab_id, ''LAB_EDIT'')')
$sqlLines.Add(')')
$sqlLines.Add('with check (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or owner_id = auth.uid()')
$sqlLines.Add('  or rgsr.has_lab_capability(labs.lab_id, ''LAB_EDIT'')')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- invites: only lab admins/owner can view/manage invites (still private)')
$sqlLines.Add('drop policy if exists li_select on rgsr.lab_invites;')
$sqlLines.Add('create policy li_select on rgsr.lab_invites for select to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or rgsr.has_lab_capability(lab_id, ''TEAM_INVITE'')')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists li_insert on rgsr.lab_invites;')
$sqlLines.Add('create policy li_insert on rgsr.lab_invites for insert to authenticated')
$sqlLines.Add('with check (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or rgsr.has_lab_capability(lab_id, ''TEAM_INVITE'')')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists li_update on rgsr.lab_invites;')
$sqlLines.Add('create policy li_update on rgsr.lab_invites for update to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or rgsr.has_lab_capability(lab_id, ''TEAM_INVITE'')')
$sqlLines.Add(')')
$sqlLines.Add('with check (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or rgsr.has_lab_capability(lab_id, ''TEAM_INVITE'')')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- user_profiles: user can edit self fields (display_name) privately')
$sqlLines.Add('-- (Your existing policies already allow self update; we keep them.)')
$sqlLines.Add('')
$sqlLines.Add('commit;')
$sqlLines.Add('')
$sqlLines.Add('-- ============================================================')
$sqlLines.Add('-- End migration')
$sqlLines.Add('-- ============================================================')

$sql = ($sqlLines -join "`r`n") + "`r`n"
WriteUtf8NoBomIfChanged $mgPath $sql
Write-Host ("[OK] MIGRATION READY: " + $mgPath) -ForegroundColor Green

if ($LinkProject) {
  if (-not $ProjectRef) {
    Write-Host "[NOTE] Paste Supabase Project Ref (Settings -> General -> Project Ref)" -ForegroundColor Yellow
    $ProjectRef = Read-Host "ProjectRef"
  }
  if (-not $ProjectRef) { throw "ProjectRef is required for link." }
  supabase link --project-ref $ProjectRef
}

if ($ApplyRemote) {
  supabase db push
}

Write-Host "✅ RGSR TEAM/SEATS/INVITES PIPELINE COMPLETE" -ForegroundColor Green

