param(
  [Parameter(Mandatory)][string]$RepoRoot,
  [string]$MigrationId = "",
  [switch]$LinkProject,
  [string]$ProjectRef = "",
  [switch]$ApplyRemote
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function EnsureDir([string]$p) { if (-not (Test-Path -LiteralPath $p)) { New-Item -ItemType Directory -Path $p -Force | Out-Null } }
function WriteUtf8NoBomIfChanged([string]$Path, [string]$Content) {
  $dir = Split-Path -Parent $Path
  if ($dir) { EnsureDir $dir }
  $enc = New-Object System.Text.UTF8Encoding($false)
  $existing = $null
  if (Test-Path -LiteralPath $Path) { $existing = Get-Content -Raw -LiteralPath $Path -Encoding UTF8 }
  if ($existing -ne $Content) {
    [IO.File]::WriteAllText($Path, $Content, $enc)
    Write-Host ("[OK] WROTE " + $Path) -ForegroundColor DarkGreen
  } else {
    Write-Host ("[OK] NO-CHANGE " + $Path) -ForegroundColor DarkCyan
  }
}

if (-not (Test-Path -LiteralPath $RepoRoot)) { throw "RepoRoot not found: $RepoRoot" }
Set-Location $RepoRoot

$mgDir = Join-Path $RepoRoot "supabase\migrations"
EnsureDir $mgDir

if (-not $MigrationId) { $MigrationId = (Get-Date).ToUniversalTime().ToString("yyyyMMddHHmmss") }
$mgPath = Join-Path $mgDir ("{0}_rgsr_env_profiles_geometry_library_and_team_rpc_v1.sql" -f $MigrationId)

# SQL body as lines -> joined (no quoting traps)
$sqlLines = New-Object System.Collections.Generic.List[string]

$sqlLines.Add('-- ============================================================')
$sqlLines.Add('-- RGSR: Env Profiles (Lane-aware) + Full Geometry Library + Team RPCs (V1)')
$sqlLines.Add('-- Canonical goals:')
$sqlLines.Add('--  - Condition profiles behave like geometry: PRIVATE / LAB / PUBLISHED (templates)')
$sqlLines.Add('--  - Seeds match UI (more than 2 models + real template catalog)')
$sqlLines.Add('--  - Team management RPCs for Profile menu (edit team / seats / overrides / invites)')
$sqlLines.Add('--  - RLS: private by default, lab-private roster, published templates globally readable')
$sqlLines.Add('-- ============================================================')
$sqlLines.Add('')
$sqlLines.Add('begin;')
$sqlLines.Add('')
$sqlLines.Add('create extension if not exists pgcrypto;')
$sqlLines.Add('')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('-- 0) Helpers')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('create or replace function rgsr._seed_owner_any_user()')
$sqlLines.Add('returns uuid language sql stable as $$')
$sqlLines.Add('  select coalesce(')
$sqlLines.Add('    (select up.user_id from rgsr.user_profiles up where up.role_id = ''SYS_ADMIN''::rgsr.rgsr_role_id order by up.created_at asc limit 1),')
$sqlLines.Add('    (select up.user_id from rgsr.user_profiles up order by up.created_at asc limit 1)')
$sqlLines.Add('  );')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.tg_touch_updated_at()')
$sqlLines.Add('returns trigger language plpgsql as $$')
$sqlLines.Add('begin')
$sqlLines.Add('  new.updated_at = now();')
$sqlLines.Add('  return new;')
$sqlLines.Add('end $$;')
$sqlLines.Add('')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('-- 1) Capabilities: Environment Profiles (Condition Profiles) + Team UI RPC gating')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('insert into rgsr.capabilities (capability_id, description) values')
$sqlLines.Add('  (''ENV_PROFILE_VIEW'',      ''View environment/condition profiles (private + lab + published)''),')
$sqlLines.Add('  (''ENV_PROFILE_CREATE'',    ''Create private environment/condition profiles''),')
$sqlLines.Add('  (''ENV_PROFILE_EDIT'',      ''Edit environment/condition profiles you own (or lab-permitted)''),')
$sqlLines.Add('  (''ENV_PROFILE_SHARE_LAB'', ''Share environment/condition profiles into LAB lane''),')
$sqlLines.Add('  (''ENV_PROFILE_TEMPLATE'',  ''Mark environment profiles as templates''),')
$sqlLines.Add('  (''ENV_PROFILE_PUBLISH'',   ''Publish environment templates (PUBLISHED lane)''),')
$sqlLines.Add('  (''TEAM_ROSTER_VIEW'',      ''View lab roster details for team management UI'' )')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- Plans: baseline view for authenticated users (tighten later if you want)')
$sqlLines.Add('insert into rgsr.plan_capabilities(plan_id, capability_id, enabled) values')
$sqlLines.Add('  (''OBSERVER_FREE'',''ENV_PROFILE_VIEW'', true),')
$sqlLines.Add('  (''RESEARCHER_PRO'',''ENV_PROFILE_VIEW'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''ENV_PROFILE_VIEW'', true),')
$sqlLines.Add('  (''INSTITUTION'',''ENV_PROFILE_VIEW'', true)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- Creation/edit by plan')
$sqlLines.Add('insert into rgsr.plan_capabilities(plan_id, capability_id, enabled) values')
$sqlLines.Add('  (''RESEARCHER_PRO'',''ENV_PROFILE_CREATE'', true),')
$sqlLines.Add('  (''RESEARCHER_PRO'',''ENV_PROFILE_EDIT'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''ENV_PROFILE_CREATE'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''ENV_PROFILE_EDIT'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''ENV_PROFILE_SHARE_LAB'', true),')
$sqlLines.Add('  (''INSTITUTION'',''ENV_PROFILE_CREATE'', true),')
$sqlLines.Add('  (''INSTITUTION'',''ENV_PROFILE_EDIT'', true),')
$sqlLines.Add('  (''INSTITUTION'',''ENV_PROFILE_SHARE_LAB'', true),')
$sqlLines.Add('  (''INSTITUTION'',''ENV_PROFILE_TEMPLATE'', true),')
$sqlLines.Add('  (''INSTITUTION'',''ENV_PROFILE_PUBLISH'', true)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- Seat (lab role) capabilities (VIEWER view-only; MEMBER create/edit own; ADMIN/OWNER share/template/publish)')
$sqlLines.Add('insert into rgsr.lab_role_capabilities (lab_role, capability_id, enabled) values')
$sqlLines.Add('  (''VIEWER'',''ENV_PROFILE_VIEW'', true),')
$sqlLines.Add('  (''MEMBER'',''ENV_PROFILE_VIEW'', true),')
$sqlLines.Add('  (''MEMBER'',''ENV_PROFILE_CREATE'', true),')
$sqlLines.Add('  (''MEMBER'',''ENV_PROFILE_EDIT'', true),')
$sqlLines.Add('  (''ADMIN'',''ENV_PROFILE_VIEW'', true),')
$sqlLines.Add('  (''ADMIN'',''ENV_PROFILE_CREATE'', true),')
$sqlLines.Add('  (''ADMIN'',''ENV_PROFILE_EDIT'', true),')
$sqlLines.Add('  (''ADMIN'',''ENV_PROFILE_SHARE_LAB'', true),')
$sqlLines.Add('  (''ADMIN'',''ENV_PROFILE_TEMPLATE'', true),')
$sqlLines.Add('  (''OWNER'',''ENV_PROFILE_VIEW'', true),')
$sqlLines.Add('  (''OWNER'',''ENV_PROFILE_CREATE'', true),')
$sqlLines.Add('  (''OWNER'',''ENV_PROFILE_EDIT'', true),')
$sqlLines.Add('  (''OWNER'',''ENV_PROFILE_SHARE_LAB'', true),')
$sqlLines.Add('  (''OWNER'',''ENV_PROFILE_TEMPLATE'', true),')
$sqlLines.Add('  (''OWNER'',''ENV_PROFILE_PUBLISH'', true),')
$sqlLines.Add('  (''ADMIN'',''TEAM_ROSTER_VIEW'', true),')
$sqlLines.Add('  (''OWNER'',''TEAM_ROSTER_VIEW'', true)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('-- 2) Upgrade rgsr.condition_profiles into lane-aware + template-capable')
$sqlLines.Add('--    (Preserves existing data; makes it per-owner and private by default)')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('alter table rgsr.condition_profiles add column if not exists lane rgsr.rgsr_lane not null default ''PRIVATE'';')
$sqlLines.Add('alter table rgsr.condition_profiles add column if not exists is_template boolean not null default false;')
$sqlLines.Add('alter table rgsr.condition_profiles add column if not exists engine_code text not null default ''RGSR'';')
$sqlLines.Add('alter table rgsr.condition_profiles add column if not exists owner_id uuid;')
$sqlLines.Add('alter table rgsr.condition_profiles add column if not exists lab_id uuid references rgsr.labs(lab_id) on delete set null;')
$sqlLines.Add('alter table rgsr.condition_profiles add column if not exists updated_at timestamptz not null default now();')
$sqlLines.Add('')
$sqlLines.Add('-- Backfill owner_id from created_by (canonical)')
$sqlLines.Add('update rgsr.condition_profiles set owner_id = created_by where owner_id is null;')
$sqlLines.Add('')
$sqlLines.Add('-- Enforce FK (only if auth.users exists row, which it does for created_by)')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_constraint where conname = ''condition_profiles_owner_fk'') then')
$sqlLines.Add('    alter table rgsr.condition_profiles')
$sqlLines.Add('      add constraint condition_profiles_owner_fk foreign key (owner_id) references auth.users(id) on delete cascade;')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- Ensure owner_id NOT NULL after backfill')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from rgsr.condition_profiles where owner_id is null) then')
$sqlLines.Add('    alter table rgsr.condition_profiles alter column owner_id set not null;')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- Drop the global UNIQUE(profile_name) if it exists; replace with per-owner uniqueness')
$sqlLines.Add('do $$')
$sqlLines.Add('declare c record;')
$sqlLines.Add('begin')
$sqlLines.Add('  for c in')
$sqlLines.Add('    select conname')
$sqlLines.Add('    from pg_constraint')
$sqlLines.Add('    join pg_class on pg_class.oid = pg_constraint.conrelid')
$sqlLines.Add('    join pg_namespace n on n.oid = pg_class.relnamespace')
$sqlLines.Add('    where n.nspname = ''rgsr'' and pg_class.relname = ''condition_profiles''')
$sqlLines.Add('      and pg_constraint.contype = ''u''')
$sqlLines.Add('  loop')
$sqlLines.Add('    -- if the constraint touches profile_name, drop it')
$sqlLines.Add('    if exists (')
$sqlLines.Add('      select 1')
$sqlLines.Add('      from pg_attribute a')
$sqlLines.Add('      join pg_constraint ct on ct.conrelid = a.attrelid')
$sqlLines.Add('      where ct.conname = c.conname and a.attname = ''profile_name'' and a.attnum = any(ct.conkey)')
$sqlLines.Add('    ) then')
$sqlLines.Add('      execute format(''alter table rgsr.condition_profiles drop constraint %I'', c.conname);')
$sqlLines.Add('    end if;')
$sqlLines.Add('  end loop;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- New uniqueness: per-owner profile_name + stable published template uniqueness')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_constraint where conname = ''condition_profiles_owner_name_uq'') then')
$sqlLines.Add('    alter table rgsr.condition_profiles add constraint condition_profiles_owner_name_uq unique (owner_id, profile_name);')
$sqlLines.Add('  end if;')
$sqlLines.Add('  if not exists (select 1 from pg_constraint where conname = ''condition_profiles_engine_name_lane_tpl_uq'') then')
$sqlLines.Add('    alter table rgsr.condition_profiles add constraint condition_profiles_engine_name_lane_tpl_uq unique (engine_code, profile_name, lane, is_template);')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- Touch trigger')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_trigger where tgname = ''tr_condition_profiles_touch'') then')
$sqlLines.Add('    create trigger tr_condition_profiles_touch')
$sqlLines.Add('    before update on rgsr.condition_profiles')
$sqlLines.Add('    for each row execute function rgsr.tg_touch_updated_at();')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- Forward-only lane for env profiles')
$sqlLines.Add('create or replace function rgsr.tg_condition_profile_lane_forward_only()')
$sqlLines.Add('returns trigger language plpgsql as $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if (tg_op = ''UPDATE'') then')
$sqlLines.Add('    if rgsr.lane_rank(new.lane) < rgsr.lane_rank(old.lane) then')
$sqlLines.Add('      raise exception ''Env profile lane is forward-only: % -> % is not allowed'', old.lane, new.lane')
$sqlLines.Add('        using errcode = ''check_violation'';')
$sqlLines.Add('    end if;')
$sqlLines.Add('  end if;')
$sqlLines.Add('  return new;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_trigger where tgname = ''tr_condition_profiles_lane_forward_only'') then')
$sqlLines.Add('    create trigger tr_condition_profiles_lane_forward_only')
$sqlLines.Add('    before update of lane on rgsr.condition_profiles')
$sqlLines.Add('    for each row execute function rgsr.tg_condition_profile_lane_forward_only();')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- Read/write helpers (env profiles)')
$sqlLines.Add('create or replace function rgsr.can_read_env_profile(p_lane rgsr.rgsr_lane, p_owner uuid, p_lab uuid)')
$sqlLines.Add('returns boolean language sql stable as $$')
$sqlLines.Add('  select rgsr.is_sys_admin()')
$sqlLines.Add('  or case p_lane')
$sqlLines.Add('    when ''PUBLISHED'' then true')
$sqlLines.Add('    when ''PRIVATE'' then (auth.uid() = p_owner) and rgsr.has_capability(''ENV_PROFILE_VIEW'')')
$sqlLines.Add('    when ''LAB'' then (p_lab is not null and rgsr.is_lab_member(p_lab) and rgsr.has_capability(''ENV_PROFILE_VIEW''))')
$sqlLines.Add('    when ''REVIEW'' then (p_lab is not null and rgsr.is_lab_member(p_lab) and rgsr.has_capability(''ENV_PROFILE_VIEW''))')
$sqlLines.Add('  end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.can_write_env_profile_target(p_lane rgsr.rgsr_lane, p_lab uuid)')
$sqlLines.Add('returns boolean language sql stable as $$')
$sqlLines.Add('  select rgsr.is_sys_admin()')
$sqlLines.Add('  or case p_lane')
$sqlLines.Add('    when ''PRIVATE'' then rgsr.has_capability(''ENV_PROFILE_CREATE'')')
$sqlLines.Add('    when ''LAB'' then (p_lab is not null and rgsr.me_has_lab_capability(p_lab, ''ENV_PROFILE_SHARE_LAB'') and rgsr.has_capability(''ENV_PROFILE_CREATE''))')
$sqlLines.Add('    when ''REVIEW'' then (p_lab is not null and rgsr.me_has_lab_capability(p_lab, ''ENV_PROFILE_SHARE_LAB'') and rgsr.has_capability(''ENV_PROFILE_CREATE''))')
$sqlLines.Add('    when ''PUBLISHED'' then rgsr.has_capability(''ENV_PROFILE_PUBLISH'')')
$sqlLines.Add('  end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('-- RLS for env profiles')
$sqlLines.Add('alter table rgsr.condition_profiles enable row level security;')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists cp_select on rgsr.condition_profiles;')
$sqlLines.Add('create policy cp_select on rgsr.condition_profiles for select to authenticated')
$sqlLines.Add('using (rgsr.can_read_env_profile(lane, owner_id, lab_id));')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists cp_insert on rgsr.condition_profiles;')
$sqlLines.Add('create policy cp_insert on rgsr.condition_profiles for insert to authenticated')
$sqlLines.Add('with check (')
$sqlLines.Add('  owner_id = auth.uid()')
$sqlLines.Add('  and rgsr.can_write_env_profile_target(lane, lab_id)')
$sqlLines.Add('  and (lab_id is null or rgsr.is_lab_member(lab_id))')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists cp_update on rgsr.condition_profiles;')
$sqlLines.Add('create policy cp_update on rgsr.condition_profiles for update to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or owner_id = auth.uid()')
$sqlLines.Add('  or (lab_id is not null and rgsr.me_has_lab_capability(lab_id, ''ENV_PROFILE_EDIT''))')
$sqlLines.Add(')')
$sqlLines.Add('with check (')
$sqlLines.Add('  rgsr.can_write_env_profile_target(lane, lab_id)')
$sqlLines.Add('  and (lab_id is null or rgsr.is_lab_member(lab_id))')
$sqlLines.Add('  and (is_template = false or (is_template = true and rgsr.has_capability(''ENV_PROFILE_TEMPLATE'')))')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists cp_delete on rgsr.condition_profiles;')
$sqlLines.Add('create policy cp_delete on rgsr.condition_profiles for delete to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or owner_id = auth.uid()')
$sqlLines.Add('  or (lab_id is not null and rgsr.me_has_lab_capability(lab_id, ''ENV_PROFILE_EDIT''))')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('-- 3) Team RPCs for Profile Menu (edit team / overrides / invites)')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('create or replace function rgsr.get_lab_team(p_lab uuid)')
$sqlLines.Add('returns jsonb')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select jsonb_build_object(')
$sqlLines.Add('    ''lab_id'', p_lab,')
$sqlLines.Add('    ''members'', coalesce((')
$sqlLines.Add('      select jsonb_agg(jsonb_build_object(')
$sqlLines.Add('        ''user_id'', up.user_id,')
$sqlLines.Add('        ''display_name'', up.display_name,')
$sqlLines.Add('        ''plan_id'', up.plan_id,')
$sqlLines.Add('        ''role_id'', up.role_id,')
$sqlLines.Add('        ''seat_role'', lm.seat_role,')
$sqlLines.Add('        ''is_owner'', (l.owner_id = up.user_id)')
$sqlLines.Add('      ) order by (l.owner_id = up.user_id) desc, lm.created_at asc),')
$sqlLines.Add('      ''[]''::jsonb')
$sqlLines.Add('    ) from rgsr.labs l')
$sqlLines.Add('      join rgsr.lab_members lm on lm.lab_id = l.lab_id')
$sqlLines.Add('      join rgsr.user_profiles up on up.user_id = lm.user_id')
$sqlLines.Add('    where l.lab_id = p_lab')
$sqlLines.Add('      and rgsr.me_has_lab_capability(p_lab, ''TEAM_ROSTER_VIEW'')')
$sqlLines.Add('      and rgsr.is_lab_member(p_lab)')
$sqlLines.Add('    )')
$sqlLines.Add('  );')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.set_lab_member_role(p_lab uuid, p_user uuid, p_role rgsr.rgsr_lab_role)')
$sqlLines.Add('returns void')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('declare')
$sqlLines.Add('  owner uuid;')
$sqlLines.Add('begin')
$sqlLines.Add('  if not rgsr.has_lab_capability(p_lab, ''TEAM_MANAGE'') then')
$sqlLines.Add('    raise exception ''not authorized'' using errcode = ''insufficient_privilege'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('')
$sqlLines.Add('  select l.owner_id into owner from rgsr.labs l where l.lab_id = p_lab;')
$sqlLines.Add('  if owner is null then return; end if;')
$sqlLines.Add('')
$sqlLines.Add('  if p_user = owner and p_role <> ''OWNER'' then')
$sqlLines.Add('    raise exception ''cannot change lab owner role'' using errcode = ''insufficient_privilege'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('')
$sqlLines.Add('  update rgsr.lab_members')
$sqlLines.Add('  set seat_role = p_role,')
$sqlLines.Add('      is_admin = (p_role in (''OWNER'',''ADMIN''))')
$sqlLines.Add('  where lab_id = p_lab and user_id = p_user;')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.remove_lab_member(p_lab uuid, p_user uuid)')
$sqlLines.Add('returns void')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('declare owner uuid;')
$sqlLines.Add('begin')
$sqlLines.Add('  if not rgsr.has_lab_capability(p_lab, ''TEAM_MANAGE'') then')
$sqlLines.Add('    raise exception ''not authorized'' using errcode = ''insufficient_privilege'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('  select l.owner_id into owner from rgsr.labs l where l.lab_id = p_lab;')
$sqlLines.Add('  if p_user = owner then')
$sqlLines.Add('    raise exception ''cannot remove lab owner'' using errcode = ''insufficient_privilege'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('  delete from rgsr.lab_member_capability_overrides where lab_id = p_lab and user_id = p_user;')
$sqlLines.Add('  delete from rgsr.lab_members where lab_id = p_lab and user_id = p_user;')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.leave_lab(p_lab uuid)')
$sqlLines.Add('returns void')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('declare owner uuid;')
$sqlLines.Add('begin')
$sqlLines.Add('  select l.owner_id into owner from rgsr.labs l where l.lab_id = p_lab;')
$sqlLines.Add('  if auth.uid() = owner then')
$sqlLines.Add('    raise exception ''owner cannot leave lab'' using errcode = ''insufficient_privilege'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('  delete from rgsr.lab_member_capability_overrides where lab_id = p_lab and user_id = auth.uid();')
$sqlLines.Add('  delete from rgsr.lab_members where lab_id = p_lab and user_id = auth.uid();')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.get_lab_invites(p_lab uuid)')
$sqlLines.Add('returns jsonb')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select jsonb_build_object(')
$sqlLines.Add('    ''lab_id'', p_lab,')
$sqlLines.Add('    ''invites'', coalesce((')
$sqlLines.Add('      select jsonb_agg(jsonb_build_object(')
$sqlLines.Add('        ''invite_id'', li.invite_id,')
$sqlLines.Add('        ''email'', li.email,')
$sqlLines.Add('        ''seat_role'', li.seat_role,')
$sqlLines.Add('        ''status'', li.status,')
$sqlLines.Add('        ''created_at'', li.created_at,')
$sqlLines.Add('        ''expires_at'', li.expires_at')
$sqlLines.Add('      ) order by li.created_at desc),')
$sqlLines.Add('      ''[]''::jsonb')
$sqlLines.Add('    ) from rgsr.lab_invites li')
$sqlLines.Add('      where li.lab_id = p_lab')
$sqlLines.Add('        and rgsr.me_has_lab_capability(p_lab, ''TEAM_INVITE'')')
$sqlLines.Add('    )')
$sqlLines.Add('  );')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.upsert_member_capability_override(p_lab uuid, p_user uuid, p_cap text, p_enabled boolean)')
$sqlLines.Add('returns void')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not rgsr.me_has_lab_capability(p_lab, ''SEAT_GRANT'') then')
$sqlLines.Add('    raise exception ''not authorized'' using errcode = ''insufficient_privilege'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('  if not exists (select 1 from rgsr.capabilities c where c.capability_id = p_cap) then')
$sqlLines.Add('    raise exception ''unknown capability'' using errcode = ''invalid_parameter_value'';')
$sqlLines.Add('  end if;')
$sqlLines.Add('  insert into rgsr.lab_member_capability_overrides(lab_id, user_id, capability_id, enabled, created_by)')
$sqlLines.Add('  values (p_lab, p_user, p_cap, p_enabled, auth.uid())')
$sqlLines.Add('  on conflict (lab_id, user_id, capability_id) do update')
$sqlLines.Add('    set enabled = excluded.enabled,')
$sqlLines.Add('        updated_at = now();')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('-- 4) Seed FULL Geometry Template Library (PUBLISHED templates)')
$sqlLines.Add('--    (Matches UI set you posted; deterministic + canonical)')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('do $$')
$sqlLines.Add('declare seed_owner uuid;')
$sqlLines.Add('begin')
$sqlLines.Add('  seed_owner := rgsr._seed_owner_any_user();')
$sqlLines.Add('  if seed_owner is null then')
$sqlLines.Add('    return;')
$sqlLines.Add('  end if;')
$sqlLines.Add('')
$sqlLines.Add('  -- Ensure template uniqueness at table level (prevents duplicates on re-run)')
$sqlLines.Add('  if not exists (select 1 from pg_constraint where conname = ''geometry_sets_engine_name_lane_tpl_uq'') then')
$sqlLines.Add('    alter table rgsr.geometry_sets add constraint geometry_sets_engine_name_lane_tpl_uq unique (engine_code, name, lane, is_template);')
$sqlLines.Add('  end if;')
$sqlLines.Add('')
$sqlLines.Add('  -- GRIDS')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''6x6 Grid'',')
$sqlLines.Add('    ''Standard grid configuration (Phase A baseline)'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(')
$sqlLines.Add('      ''type'',''grid'',''rows'',6,''cols'',6,''category'',''Grid'',')
$sqlLines.Add('      ''nodes'', (')
$sqlLines.Add('        select jsonb_agg(jsonb_build_object(')
$sqlLines.Add('          ''id'', format(''%s%s'', chr(64+xc), yc),')
$sqlLines.Add('          ''x'', xc, ''y'', yc')
$sqlLines.Add('        ) order by yc, xc)')
$sqlLines.Add('        from generate_series(1,6) yc cross join generate_series(1,6) xc')
$sqlLines.Add('      )')
$sqlLines.Add('    ),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''spacing'',jsonb_build_object(''x'',10,''y'',10),''origin'',jsonb_build_object(''x'',0,''y'',0))')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''8x8 Grid'',')
$sqlLines.Add('    ''Expanded grid layout (higher node density)'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(')
$sqlLines.Add('      ''type'',''grid'',''rows'',8,''cols'',8,''category'',''Grid'',')
$sqlLines.Add('      ''nodes'', (')
$sqlLines.Add('        select jsonb_agg(jsonb_build_object(')
$sqlLines.Add('          ''id'', format(''%s%s'', chr(64+xc), yc),')
$sqlLines.Add('          ''x'', xc, ''y'', yc')
$sqlLines.Add('        ) order by yc, xc)')
$sqlLines.Add('        from generate_series(1,8) yc cross join generate_series(1,8) xc')
$sqlLines.Add('      )')
$sqlLines.Add('    ),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''spacing'',jsonb_build_object(''x'',10,''y'',10),''origin'',jsonb_build_object(''x'',0,''y'',0))')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''12x12 Grid'',')
$sqlLines.Add('    ''Large-scale grid pattern (stress & stability testing)'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(')
$sqlLines.Add('      ''type'',''grid'',''rows'',12,''cols'',12,''category'',''Grid'',')
$sqlLines.Add('      ''nodes'', (')
$sqlLines.Add('        select jsonb_agg(jsonb_build_object(')
$sqlLines.Add('          ''id'', format(''%s%s'', chr(64+xc), yc),')
$sqlLines.Add('          ''x'', xc, ''y'', yc')
$sqlLines.Add('        ) order by yc, xc)')
$sqlLines.Add('        from generate_series(1,12) yc cross join generate_series(1,12) xc')
$sqlLines.Add('      )')
$sqlLines.Add('    ),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''spacing'',jsonb_build_object(''x'',8,''y'',8),''origin'',jsonb_build_object(''x'',0,''y'',0))')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  -- PYRAMIDS')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''Pyramid (4-sided)'',')
$sqlLines.Add('    ''Classic tetrahedron-style pyramid mapping placeholder'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(''type'',''pyramid'',''sides'',4,''tiers'',4,''category'',''Geometric'',''notes'',''Symbolic topology; wire real coordinates when instrumentation is defined.''),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''bounds'',jsonb_build_object(''width'',60,''depth'',60,''height'',50))')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''Pyramid (8-sided)'',')
$sqlLines.Add('    ''Octagonal pyramid mapping placeholder'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(''type'',''pyramid'',''sides'',8,''tiers'',5,''category'',''Geometric'',''notes'',''Symbolic topology; wire real coordinates when instrumentation is defined.''),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''bounds'',jsonb_build_object(''width'',80,''depth'',80,''height'',60))')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  -- LATTICES / PATTERNS (generator-style)')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''Hexagonal Lattice'',')
$sqlLines.Add('    ''Honeycomb structure (lattice coupling tests)'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(''type'',''hex_lattice'',''category'',''Lattice'',''generator'',jsonb_build_object(''rings'',4,''spacing_cm'',8)),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''notes'',''Generator-defined lattice; engine expands nodes.'' )')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''Triangular Grid'',')
$sqlLines.Add('    ''Triangular tessellation (anisotropy tests)'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(''type'',''tri_grid'',''category'',''Pattern'',''generator'',jsonb_build_object(''rows'',8,''cols'',8,''spacing_cm'',8)),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''notes'',''Generator-defined; engine expands.'' )')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''Voronoi Diagram'',')
$sqlLines.Add('    ''Organic cell-like pattern (heterogeneity tests)'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(''type'',''voronoi'',''category'',''Pattern'',''generator'',jsonb_build_object(''seeds'',24,''bounds_cm'',jsonb_build_object(''w'',80,''h'',80))),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''notes'',''Generator-defined; deterministic via run hash seed.'' )')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''Fibonacci Spiral'',')
$sqlLines.Add('    ''Golden ratio spiral (pattern resonance tests)'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(''type'',''fibonacci_spiral'',''category'',''Pattern'',''generator'',jsonb_build_object(''turns'',6,''points'',144,''scale_cm'',80)),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''notes'',''Generator-defined; deterministic.'' )')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''Double Helix'',')
$sqlLines.Add('    ''DNA-style helix structure (coupling tests)'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(''type'',''double_helix'',''category'',''Pattern'',''generator'',jsonb_build_object(''turns'',5,''radius_cm'',12,''height_cm'',60,''points_per_turn'',48)),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''notes'',''Generator-defined.'' )')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''Fractal Pattern'',')
$sqlLines.Add('    ''Self-similar structure (multi-scale stability tests)'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(''type'',''fractal'',''category'',''Pattern'',''generator'',jsonb_build_object(''kind'',''sierpinski'',''depth'',4,''scale_cm'',80)),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''notes'',''Generator-defined.'' )')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  -- VOLUMES (explicit nodes)')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''4x4x4 Cube'',')
$sqlLines.Add('    ''3D volumetric cube (64 nodes)'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(')
$sqlLines.Add('      ''type'',''cube'',''nx'',4,''ny'',4,''nz'',4,''category'',''Volume'',')
$sqlLines.Add('      ''nodes'', (')
$sqlLines.Add('        select jsonb_agg(jsonb_build_object(')
$sqlLines.Add('          ''id'', format(''C%02s_%02s_%02s'', x, y, z),')
$sqlLines.Add('          ''x'', x, ''y'', y, ''z'', z')
$sqlLines.Add('        ) order by z, y, x)')
$sqlLines.Add('        from generate_series(1,4) x cross join generate_series(1,4) y cross join generate_series(1,4) z')
$sqlLines.Add('      )')
$sqlLines.Add('    ),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''spacing'',jsonb_build_object(''x'',8,''y'',8,''z'',8),''origin'',jsonb_build_object(''x'',0,''y'',0,''z'',0))')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''6x6x6 Cube'',')
$sqlLines.Add('    ''Large volume cube (216 nodes)'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(')
$sqlLines.Add('      ''type'',''cube'',''nx'',6,''ny'',6,''nz'',6,''category'',''Volume'',')
$sqlLines.Add('      ''nodes'', (')
$sqlLines.Add('        select jsonb_agg(jsonb_build_object(')
$sqlLines.Add('          ''id'', format(''C%02s_%02s_%02s'', x, y, z),')
$sqlLines.Add('          ''x'', x, ''y'', y, ''z'', z')
$sqlLines.Add('        ) order by z, y, x)')
$sqlLines.Add('        from generate_series(1,6) x cross join generate_series(1,6) y cross join generate_series(1,6) z')
$sqlLines.Add('      )')
$sqlLines.Add('    ),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''spacing'',jsonb_build_object(''x'',7,''y'',7,''z'',7),''origin'',jsonb_build_object(''x'',0,''y'',0,''z'',0))')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  -- GEODESIC / TORUS / DIAMOND (generator style)')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''Sphere (Geodesic)'',')
$sqlLines.Add('    ''Spherical distribution (geodesic sampling)'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(''type'',''geodesic_sphere'',''category'',''Geometric'',''generator'',jsonb_build_object(''subdivisions'',2,''radius_cm'',35,''nodes_target'',128)),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''notes'',''Generator-defined geodesic points.'' )')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''Torus'',')
$sqlLines.Add('    ''Donut-shaped configuration (ring coupling tests)'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(''type'',''torus'',''category'',''Geometric'',''generator'',jsonb_build_object(''major_radius_cm'',35,''minor_radius_cm'',12,''u_steps'',24,''v_steps'',12)),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''notes'',''Generator-defined torus mesh.'' )')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.geometry_sets(name, description, lane, is_template, engine_code, owner_id, lab_id, geometry_json, dims_json)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''Diamond Lattice'',')
$sqlLines.Add('    ''Crystal lattice pattern (structure resonance tests)'',')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null,')
$sqlLines.Add('    jsonb_build_object(''type'',''diamond_lattice'',''category'',''Lattice'',''generator'',jsonb_build_object(''cells'',3,''spacing_cm'',10)),')
$sqlLines.Add('    jsonb_build_object(''units'',''cm'',''notes'',''Generator-defined lattice.'' )')
$sqlLines.Add('  ) on conflict on constraint geometry_sets_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('-- 5) Seed Condition Profile templates (PUBLISHED)')
$sqlLines.Add('--    Matches UI Saved Profiles panel (DRY_BASELINE_V1 / WATER_STATIC_20MM / HUMID_WARM_FLOW)')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('do $$')
$sqlLines.Add('declare seed_owner uuid;')
$sqlLines.Add('begin')
$sqlLines.Add('  seed_owner := rgsr._seed_owner_any_user();')
$sqlLines.Add('  if seed_owner is null then return; end if;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.condition_profiles(profile_name, profile_json, created_by, created_at, lane, is_template, engine_code, owner_id, lab_id, updated_at)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''DRY_BASELINE_V1'',')
$sqlLines.Add('    jsonb_build_object(')
$sqlLines.Add('      ''temperature'', jsonb_build_object(''external_c'',20.0,''internal_c'',20.0,''water_c'',0.0),')
$sqlLines.Add('      ''water_system'', jsonb_build_object(''volume_mm'',0,''salinity_psu'',0.0,''flow_lpm'',0.0,''material_moisture_pct'',0.0),')
$sqlLines.Add('      ''environment'', jsonb_build_object(''humidity_rh'',40,''pressure_hpa'',1013,''seasonal_profile'',''CONTROLLED''),')
$sqlLines.Add('      ''notes'',''Canonical dry baseline.''')
$sqlLines.Add('    ),')
$sqlLines.Add('    seed_owner, now(),')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null, now()')
$sqlLines.Add('  ) on conflict on constraint condition_profiles_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.condition_profiles(profile_name, profile_json, created_by, created_at, lane, is_template, engine_code, owner_id, lab_id, updated_at)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''WATER_STATIC_20MM'',')
$sqlLines.Add('    jsonb_build_object(')
$sqlLines.Add('      ''temperature'', jsonb_build_object(''external_c'',20.0,''internal_c'',20.0,''water_c'',20.0),')
$sqlLines.Add('      ''water_system'', jsonb_build_object(''volume_mm'',20,''salinity_psu'',0.0,''flow_lpm'',0.0,''material_moisture_pct'',0.0),')
$sqlLines.Add('      ''environment'', jsonb_build_object(''humidity_rh'',65,''pressure_hpa'',1013,''seasonal_profile'',''CONTROLLED''),')
$sqlLines.Add('      ''notes'',''Static water at 20mm depth.''')
$sqlLines.Add('    ),')
$sqlLines.Add('    seed_owner, now(),')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null, now()')
$sqlLines.Add('  ) on conflict on constraint condition_profiles_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('')
$sqlLines.Add('  insert into rgsr.condition_profiles(profile_name, profile_json, created_by, created_at, lane, is_template, engine_code, owner_id, lab_id, updated_at)')
$sqlLines.Add('  values (')
$sqlLines.Add('    ''HUMID_WARM_FLOW'',')
$sqlLines.Add('    jsonb_build_object(')
$sqlLines.Add('      ''temperature'', jsonb_build_object(''external_c'',22.0,''internal_c'',22.0,''water_c'',24.0),')
$sqlLines.Add('      ''water_system'', jsonb_build_object(''volume_mm'',50,''salinity_psu'',0.0,''flow_lpm'',1.5,''material_moisture_pct'',0.0),')
$sqlLines.Add('      ''environment'', jsonb_build_object(''humidity_rh'',80,''pressure_hpa'',1013,''seasonal_profile'',''SUMMER''),')
$sqlLines.Add('      ''notes'',''Humid warm flow profile for damping/coupling.''')
$sqlLines.Add('    ),')
$sqlLines.Add('    seed_owner, now(),')
$sqlLines.Add('    ''PUBLISHED'', true, ''RGSR'', seed_owner, null, now()')
$sqlLines.Add('  ) on conflict on constraint condition_profiles_engine_name_lane_tpl_uq do nothing;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('-- 6) Grants: lock down security-definer RPC surface to authenticated')
$sqlLines.Add('-- ------------------------------------------------------------')
$sqlLines.Add('revoke all on function rgsr.set_lab_member_role(uuid, uuid, rgsr.rgsr_lab_role) from public;')
$sqlLines.Add('revoke all on function rgsr.remove_lab_member(uuid, uuid) from public;')
$sqlLines.Add('revoke all on function rgsr.leave_lab(uuid) from public;')
$sqlLines.Add('revoke all on function rgsr.upsert_member_capability_override(uuid, uuid, text, boolean) from public;')
$sqlLines.Add('')
$sqlLines.Add('grant execute on function rgsr.set_lab_member_role(uuid, uuid, rgsr.rgsr_lab_role) to authenticated;')
$sqlLines.Add('grant execute on function rgsr.remove_lab_member(uuid, uuid) to authenticated;')
$sqlLines.Add('grant execute on function rgsr.leave_lab(uuid) to authenticated;')
$sqlLines.Add('grant execute on function rgsr.upsert_member_capability_override(uuid, uuid, text, boolean) to authenticated;')
$sqlLines.Add('')
$sqlLines.Add('commit;')
$sqlLines.Add('')
$sqlLines.Add('-- ============================================================')
$sqlLines.Add('-- End migration')
$sqlLines.Add('-- ============================================================')

$sql = ($sqlLines -join "`r`n") + "`r`n"

WriteUtf8NoBomIfChanged $mgPath $sql
Write-Host ("[OK] MIGRATION READY: " + $mgPath) -ForegroundColor Green

if ($LinkProject) {
  if (-not $ProjectRef) {
    Write-Host "[NOTE] Paste Supabase Project Ref (Settings -> General -> Project Ref)" -ForegroundColor Yellow
    $ProjectRef = Read-Host "ProjectRef"
  }
  if (-not $ProjectRef) { throw "ProjectRef is required for link." }
  supabase link --project-ref $ProjectRef
}

if ($ApplyRemote) {
  supabase db push
}

Write-Host "✅ RGSR ENV PROFILES + GEOMETRY LIBRARY + TEAM RPC PIPELINE COMPLETE" -ForegroundColor Green

