param(
  [Parameter(Mandatory)][string]$RepoRoot,
  [switch]$LinkProject,
  [string]$ProjectRef = "",
  [switch]$ApplyRemote
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function EnsureDir([string]$p) {
  if (-not (Test-Path -LiteralPath $p)) { New-Item -ItemType Directory -Path $p -Force | Out-Null }
}

function WriteUtf8NoBom([string]$Path, [string]$Content) {
  $dir = Split-Path -Parent $Path
  if ($dir) { EnsureDir $dir }
  [IO.File]::WriteAllText($Path, $Content, (New-Object Text.UTF8Encoding($false)))
  Write-Host ("[OK] WROTE " + $Path) -ForegroundColor DarkGreen
}

if (-not (Test-Path -LiteralPath $RepoRoot)) { throw "RepoRoot not found: $RepoRoot" }
Set-Location $RepoRoot

$mgDir = Join-Path $RepoRoot "supabase\migrations"
EnsureDir $mgDir

Write-Host ("[INFO] RepoRoot=" + $RepoRoot) -ForegroundColor Gray
Write-Host ("[INFO] mgDir=" + $mgDir) -ForegroundColor Gray

if ($LinkProject -or $ApplyRemote) {
  $sb = (Get-Command supabase -ErrorAction SilentlyContinue)
  if (-not $sb) { throw "supabase CLI not found in PATH." }
}

$MigrationId = (Get-Date).ToUniversalTime().ToString("yyyyMMddHHmmss")
$mgPath = Join-Path $mgDir ("{0}_rgsr_research_and_conditions_v1.sql" -f $MigrationId)

# CRITICAL: Use single-quoted lines so PowerShell never expands $do$ / $sql$ / $fn$
$sqlLines = @(
'-- ============================================================',
'-- RGSR: Research + Canonical Conditions (PHYSICS-FIRST / GOVERNED)',
'-- 1) Research:',
'--    - Admin-approved by default',
'--    - Vetted submitter bypass: users w/ >=5 approvals can publish w/o approval',
'--    - Public feed only shows description/results if contributor opted-in',
'-- 2) Canonical run conditions snapshot:',
'--    - incoming water temp, existing water temp, weather, EM, materials/geology links',
'-- ============================================================',
'',
'begin;',
'',
'-- 0) Minimal governance helpers (idempotent)',
'create or replace function rgsr.is_sys_admin()',
'returns boolean',
'language sql stable as $sql$',
'  select coalesce((select (auth.jwt() -> ''app_metadata'' ->> ''role'') = ''sys_admin''), false);',
'$sql$;',
'',
'create or replace function rgsr.is_service_role()',
'returns boolean',
'language sql stable as $sql$',
'  select coalesce((select (auth.jwt() ->> ''role'') = ''service_role''), false);',
'$sql$;',
'',
'create or replace function rgsr.me()',
'returns uuid',
'language sql stable as $sql$',
'  select auth.uid();',
'$sql$;',
'',
'-- 1) Research: canonical, governed',
'create table if not exists rgsr.research_submitter_stats (',
'  user_id uuid primary key references auth.users(id) on delete cascade,',
'  approvals_count integer not null default 0,',
'  rejections_count integer not null default 0,',
'  last_approved_at timestamptz null,',
'  last_rejected_at timestamptz null,',
'  updated_at timestamptz not null default now(),',
'  constraint rss_approvals_chk check (approvals_count >= 0),',
'  constraint rss_rejections_chk check (rejections_count >= 0)',
');',
'create index if not exists ix_rss_approvals on rgsr.research_submitter_stats(approvals_count);',
'',
'create or replace function rgsr.is_vetted_research_submitter(p_user uuid)',
'returns boolean',
'language sql stable as $sql$',
'  select rgsr.is_sys_admin()',
'     or exists (select 1 from rgsr.research_submitter_stats s where s.user_id = p_user and s.approvals_count >= 5);',
'$sql$;',
'',
'create table if not exists rgsr.research_entries (',
'  research_id uuid primary key default gen_random_uuid(),',
'  lane text not null default ''PUBLIC'',',
'  lab_id uuid null,',
'  status text not null default ''SUBMITTED'',',
'  title text not null,',
'  abstract text not null,',
'  keywords text[] not null default ''{}''::text[],',
'  methods_summary text null,',
'  instrumentation_summary text null,',
'  submitted_by uuid not null references auth.users(id) on delete restrict,',
'  submitted_at timestamptz not null default now(),',
'  approved_by uuid null references auth.users(id) on delete set null,',
'  approved_at timestamptz null,',
'  published_at timestamptz null,',
'  metadata jsonb not null default ''{}''::jsonb,',
'  constraint re_lane_chk check (lane in (''PUBLIC'',''LAB'',''INTERNAL'')),',
'  constraint re_status_chk check (status in (''DRAFT'',''SUBMITTED'',''APPROVED'',''REJECTED'',''PUBLISHED''))',
');',
'create index if not exists ix_research_entries_status on rgsr.research_entries(status);',
'create index if not exists ix_research_entries_lane on rgsr.research_entries(lane);',
'create index if not exists ix_research_entries_submitted_by on rgsr.research_entries(submitted_by);',
'',
'create table if not exists rgsr.research_reviews (',
'  review_id uuid primary key default gen_random_uuid(),',
'  research_id uuid not null references rgsr.research_entries(research_id) on delete cascade,',
'  reviewer_id uuid not null references auth.users(id) on delete restrict,',
'  decision text not null,',
'  notes text null,',
'  created_at timestamptz not null default now(),',
'  constraint rr_decision_chk check (decision in (''APPROVE'',''REJECT'',''PUBLISH''))',
');',
'create index if not exists ix_research_reviews_research on rgsr.research_reviews(research_id);',
'create index if not exists ix_research_reviews_reviewer on rgsr.research_reviews(reviewer_id);',
'',
'create table if not exists rgsr.research_results (',
'  result_id uuid primary key default gen_random_uuid(),',
'  research_id uuid not null references rgsr.research_entries(research_id) on delete cascade,',
'  result_kind text not null,',
'  result_payload jsonb not null,',
'  result_hash text not null,',
'  created_at timestamptz not null default now(),',
'  constraint rr_kind_chk check (length(result_kind) > 0),',
'  constraint rr_hash_chk check (length(result_hash) >= 16)',
');',
'create index if not exists ix_research_results_research on rgsr.research_results(research_id);',
'create index if not exists ix_research_results_kind on rgsr.research_results(result_kind);',
'',
'create table if not exists rgsr.research_contributor_optins (',
'  optin_id uuid primary key default gen_random_uuid(),',
'  research_id uuid not null references rgsr.research_entries(research_id) on delete cascade,',
'  user_id uuid not null references auth.users(id) on delete cascade,',
'  show_description boolean not null default false,',
'  show_results boolean not null default false,',
'  created_at timestamptz not null default now(),',
'  updated_at timestamptz not null default now(),',
'  constraint rco_unique unique (research_id, user_id)',
');',
'create index if not exists ix_rco_research on rgsr.research_contributor_optins(research_id);',
'create index if not exists ix_rco_user on rgsr.research_contributor_optins(user_id);',
'',
'create or replace view rgsr.v_public_research as',
'select',
'  e.research_id,',
'  e.title,',
'  e.keywords,',
'  e.published_at,',
'  case when exists (select 1 from rgsr.research_contributor_optins o where o.research_id = e.research_id and o.show_description = true)',
'       then e.abstract else null end as public_abstract,',
'  case when exists (select 1 from rgsr.research_contributor_optins o where o.research_id = e.research_id and o.show_results = true)',
'       and exists (select 1 from rgsr.research_results r where r.research_id = e.research_id)',
'       then true else false end as public_has_results',
'from rgsr.research_entries e',
'where e.status = ''PUBLISHED'';',
'',
'-- 2) Run conditions snapshot',
'create table if not exists rgsr.run_conditions (',
'  condition_id uuid primary key default gen_random_uuid(),',
'  lane text not null default ''LAB'',',
'  lab_id uuid null,',
'  run_id uuid null,',
'  recorded_at timestamptz not null default now(),',
'  water_existing_temp_c numeric null,',
'  water_incoming_temp_c numeric null,',
'  water_flow_rate_l_min numeric null,',
'  water_depth_m numeric null,',
'  water_salinity_ppm numeric null,',
'  water_turbulence_index numeric null,',
'  water_stratification_index numeric null,',
'  container_material_id uuid null,',
'  chamber_structure_id uuid null,',
'  substrate_structure_id uuid null,',
'  season text null,',
'  weather_pattern text null,',
'  wind_m_s numeric null,',
'  barometric_kpa numeric null,',
'  humidity_frac numeric null,',
'  air_density_kg_m3 numeric null,',
'  background_em_uT numeric null,',
'  induced_field_uT numeric null,',
'  field_orientation_deg numeric null,',
'  shielding_index numeric null,',
'  notes text null,',
'  metadata jsonb not null default ''{}''::jsonb,',
'  constraint rc_lane_chk check (lane in (''PUBLIC'',''LAB'',''INTERNAL'')),',
'  constraint rc_humidity_chk check (humidity_frac is null or (humidity_frac >= 0 and humidity_frac <= 1)),',
'  constraint rc_turb_chk check (water_turbulence_index is null or (water_turbulence_index >= 0 and water_turbulence_index <= 1)),',
'  constraint rc_strat_chk check (water_stratification_index is null or (water_stratification_index >= 0 and water_stratification_index <= 1)),',
'  constraint rc_shield_chk check (shielding_index is null or (shielding_index >= 0 and shielding_index <= 1)),',
'  constraint rc_orient_chk check (field_orientation_deg is null or (field_orientation_deg >= 0 and field_orientation_deg <= 360))',
');',
'create index if not exists ix_run_conditions_run on rgsr.run_conditions(run_id);',
'create index if not exists ix_run_conditions_lab on rgsr.run_conditions(lab_id);',
'create index if not exists ix_run_conditions_recorded on rgsr.run_conditions(recorded_at);',
'',
'-- 3) Optional FK attachments (introspection)',
'do $do$',
'begin',
'  if exists (select 1 from information_schema.tables where table_schema=''rgsr'' and table_name=''runs'')',
'     and exists (select 1 from information_schema.columns where table_schema=''rgsr'' and table_name=''runs'' and column_name in (''run_id'',''id'')) then',
'    begin',
'      if exists (select 1 from information_schema.columns where table_schema=''rgsr'' and table_name=''runs'' and column_name=''run_id'') then',
'        execute ''alter table rgsr.run_conditions add constraint fk_run_conditions_run foreign key (run_id) references rgsr.runs(run_id) on delete set null'';',
'      else',
'        execute ''alter table rgsr.run_conditions add constraint fk_run_conditions_run foreign key (run_id) references rgsr.runs(id) on delete set null'';',
'      end if;',
'    exception when duplicate_object then null;',
'    end;',
'  end if;',
'',
'  if exists (select 1 from information_schema.tables where table_schema=''rgsr'' and table_name=''material_profiles'') then',
'    begin',
'      execute ''alter table rgsr.run_conditions add constraint fk_rc_container_material foreign key (container_material_id) references rgsr.material_profiles(material_id) on delete set null'';',
'    exception when duplicate_object then null;',
'    end;',
'  end if;',
'',
'  if exists (select 1 from information_schema.tables where table_schema=''rgsr'' and table_name=''geology_structures'') then',
'    begin',
'      execute ''alter table rgsr.run_conditions add constraint fk_rc_chamber_structure foreign key (chamber_structure_id) references rgsr.geology_structures(structure_id) on delete set null'';',
'    exception when duplicate_object then null;',
'    end;',
'    begin',
'      execute ''alter table rgsr.run_conditions add constraint fk_rc_substrate_structure foreign key (substrate_structure_id) references rgsr.geology_structures(structure_id) on delete set null'';',
'    exception when duplicate_object then null;',
'    end;',
'  end if;',
'end',
'$do$;',
'',
'-- 4) RLS',
'alter table rgsr.research_submitter_stats enable row level security;',
'alter table rgsr.research_entries enable row level security;',
'alter table rgsr.research_reviews enable row level security;',
'alter table rgsr.research_results enable row level security;',
'alter table rgsr.research_contributor_optins enable row level security;',
'alter table rgsr.run_conditions enable row level security;',
'',
'drop policy if exists re_select on rgsr.research_entries;',
'create policy re_select on rgsr.research_entries for select to authenticated',
'using (status = ''PUBLISHED'' or submitted_by = rgsr.me() or rgsr.is_sys_admin() or rgsr.is_service_role());',
'',
'drop policy if exists re_write_block on rgsr.research_entries;',
'create policy re_write_block on rgsr.research_entries for all to authenticated',
'using (rgsr.is_sys_admin() or rgsr.is_service_role())',
'with check (rgsr.is_sys_admin() or rgsr.is_service_role());',
'',
'drop policy if exists rr_block on rgsr.research_reviews;',
'create policy rr_block on rgsr.research_reviews for all to authenticated',
'using (rgsr.is_sys_admin() or rgsr.is_service_role())',
'with check (rgsr.is_sys_admin() or rgsr.is_service_role());',
'',
'drop policy if exists rres_block on rgsr.research_results;',
'create policy rres_block on rgsr.research_results for all to authenticated',
'using (rgsr.is_sys_admin() or rgsr.is_service_role())',
'with check (rgsr.is_sys_admin() or rgsr.is_service_role());',
'',
'drop policy if exists rco_select on rgsr.research_contributor_optins;',
'create policy rco_select on rgsr.research_contributor_optins for select to authenticated',
'using (user_id = rgsr.me() or rgsr.is_sys_admin() or rgsr.is_service_role());',
'',
'drop policy if exists rco_write on rgsr.research_contributor_optins;',
'create policy rco_write on rgsr.research_contributor_optins for insert to authenticated',
'with check (user_id = rgsr.me() or rgsr.is_sys_admin() or rgsr.is_service_role());',
'',
'drop policy if exists rco_update on rgsr.research_contributor_optins;',
'create policy rco_update on rgsr.research_contributor_optins for update to authenticated',
'using (user_id = rgsr.me() or rgsr.is_sys_admin() or rgsr.is_service_role())',
'with check (user_id = rgsr.me() or rgsr.is_sys_admin() or rgsr.is_service_role());',
'',
'drop policy if exists rss_block on rgsr.research_submitter_stats;',
'create policy rss_block on rgsr.research_submitter_stats for all to authenticated',
'using (rgsr.is_sys_admin() or rgsr.is_service_role())',
'with check (rgsr.is_sys_admin() or rgsr.is_service_role());',
'',
'drop policy if exists rc_select on rgsr.run_conditions;',
'create policy rc_select on rgsr.run_conditions for select to authenticated',
'using (rgsr.is_sys_admin() or rgsr.is_service_role());',
'',
'drop policy if exists rc_write on rgsr.run_conditions;',
'create policy rc_write on rgsr.run_conditions for insert to authenticated',
'with check (rgsr.is_sys_admin() or rgsr.is_service_role());',
'',
'drop policy if exists rc_update on rgsr.run_conditions;',
'create policy rc_update on rgsr.run_conditions for update to authenticated',
'using (rgsr.is_sys_admin() or rgsr.is_service_role())',
'with check (rgsr.is_sys_admin() or rgsr.is_service_role());',
'',
'-- 5) RPCs (canonical mutation path)',
'create or replace function rgsr.submit_research(',
'  p_lane text,',
'  p_lab_id uuid,',
'  p_title text,',
'  p_abstract text,',
'  p_keywords text[],',
'  p_methods_summary text,',
'  p_instrumentation_summary text,',
'  p_metadata jsonb,',
'  p_publish_immediately boolean default false,',
'  p_results jsonb default null,',
'  p_result_kind text default ''SUMMARY'',',
'  p_result_hash text default null',
')',
'returns uuid',
'language plpgsql',
'security definer',
'set search_path = public, rgsr, auth',
'as $fn$',
'declare',
'  v_user uuid := auth.uid();',
'  v_id uuid;',
'  v_vetted boolean;',
'  v_lane text := coalesce(p_lane,''PUBLIC'');',
'  v_status text;',
'begin',
'  if v_user is null then raise exception ''not authenticated''; end if;',
'  if v_lane not in (''PUBLIC'',''LAB'',''INTERNAL'') then raise exception ''invalid lane''; end if;',
'  v_vetted := rgsr.is_vetted_research_submitter(v_user);',
'  if v_vetted and p_publish_immediately then v_status := ''PUBLISHED''; else v_status := ''SUBMITTED''; end if;',
'  insert into rgsr.research_entries(',
'    lane, lab_id, status, title, abstract, keywords,',
'    methods_summary, instrumentation_summary,',
'    submitted_by, metadata, published_at',
'  ) values (',
'    v_lane, p_lab_id, v_status, p_title, p_abstract, coalesce(p_keywords,''{}''::text[]),',
'    p_methods_summary, p_instrumentation_summary,',
'    v_user, coalesce(p_metadata,''{}''::jsonb),',
'    case when v_status=''PUBLISHED'' then now() else null end',
'  ) returning research_id into v_id;',
'',
'  if p_results is not null then',
'    if p_result_hash is null then raise exception ''result_hash required when results provided''; end if;',
'    insert into rgsr.research_results(research_id, result_kind, result_payload, result_hash)',
'    values (v_id, coalesce(p_result_kind,''SUMMARY''), p_results, p_result_hash);',
'  end if;',
'',
'  insert into rgsr.research_contributor_optins(research_id, user_id, show_description, show_results)',
'  values (v_id, v_user, false, false)',
'  on conflict (research_id, user_id) do nothing;',
'',
'  return v_id;',
'end',
'$fn$;',
'grant execute on function rgsr.submit_research(text,uuid,text,text,text[],text,text,jsonb,boolean,jsonb,text,text) to authenticated;',
'',
'create or replace function rgsr.review_research(',
'  p_research_id uuid,',
'  p_decision text,',
'  p_notes text default null',
')',
'returns void',
'language plpgsql',
'security definer',
'set search_path = public, rgsr, auth',
'as $fn$',
'declare',
'  v_admin uuid := auth.uid();',
'  v_submitter uuid;',
'begin',
'  if not (rgsr.is_sys_admin() or rgsr.is_service_role()) then raise exception ''not authorized''; end if;',
'  if p_decision not in (''APPROVE'',''REJECT'',''PUBLISH'') then raise exception ''invalid decision''; end if;',
'  select submitted_by into v_submitter from rgsr.research_entries where research_id = p_research_id;',
'  if v_submitter is null then raise exception ''research not found''; end if;',
'  insert into rgsr.research_reviews(research_id, reviewer_id, decision, notes)',
'  values (p_research_id, v_admin, p_decision, p_notes);',
'',
'  if p_decision = ''REJECT'' then',
'    update rgsr.research_entries set status=''REJECTED'', approved_by=v_admin, approved_at=now() where research_id=p_research_id;',
'    insert into rgsr.research_submitter_stats(user_id, rejections_count, last_rejected_at, updated_at)',
'    values (v_submitter, 1, now(), now())',
'    on conflict (user_id) do update set rejections_count = rgsr.research_submitter_stats.rejections_count + 1, last_rejected_at=now(), updated_at=now();',
'  elsif p_decision = ''APPROVE'' then',
'    update rgsr.research_entries set status=''APPROVED'', approved_by=v_admin, approved_at=now() where research_id=p_research_id;',
'    insert into rgsr.research_submitter_stats(user_id, approvals_count, last_approved_at, updated_at)',
'    values (v_submitter, 1, now(), now())',
'    on conflict (user_id) do update set approvals_count = rgsr.research_submitter_stats.approvals_count + 1, last_approved_at=now(), updated_at=now();',
'  else',
'    update rgsr.research_entries set status=''PUBLISHED'', approved_by=v_admin, approved_at=now(), published_at=coalesce(published_at, now()) where research_id=p_research_id;',
'    insert into rgsr.research_submitter_stats(user_id, approvals_count, last_approved_at, updated_at)',
'    values (v_submitter, 1, now(), now())',
'    on conflict (user_id) do update set approvals_count = rgsr.research_submitter_stats.approvals_count + 1, last_approved_at=now(), updated_at=now();',
'  end if;',
'end',
'$fn$;',
'grant execute on function rgsr.review_research(uuid,text,text) to authenticated;',
'',
'create or replace function rgsr.list_public_research()',
'returns setof rgsr.v_public_research',
'language sql stable',
'as $sql$',
'  select * from rgsr.v_public_research order by published_at desc nulls last;',
'$sql$;',
'grant execute on function rgsr.list_public_research() to authenticated;',
'',
'commit;',
'-- ============================================================',
'-- End migration',
'-- ============================================================'
)

$sql = ($sqlLines -join "`r`n") + "`r`n"
WriteUtf8NoBom $mgPath $sql
Write-Host ("[OK] NEW MIGRATION READY: " + $mgPath) -ForegroundColor Green

if ($LinkProject) {
  if (-not $ProjectRef) { throw "ProjectRef is required for link." }
  & supabase link --project-ref $ProjectRef
  Write-Host "[OK] supabase link complete" -ForegroundColor Green
}

if ($ApplyRemote) {
  cmd /c "echo y| supabase db push"
  Write-Host "[OK] supabase db push complete" -ForegroundColor Green
}

Write-Host "✅ ONE-SHOT PIPELINE COMPLETE (v9.1 research+conditions)" -ForegroundColor Green