param(
  [string]$RepoRoot = "",
  [string]$MigrationId = "",
  [switch]$LinkProject,
  [string]$ProjectRef = "",
  [switch]$ApplyRemote
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function EnsureDir([string]$p) { if (-not (Test-Path -LiteralPath $p)) { New-Item -ItemType Directory -Path $p -Force | Out-Null } }
function WriteUtf8NoBomIfChanged([string]$Path, [string]$Content) {
  $dir = Split-Path -Parent $Path
  if ($dir) { EnsureDir $dir }
  $enc = New-Object System.Text.UTF8Encoding($false)
  $existing = $null
  if (Test-Path -LiteralPath $Path) { $existing = Get-Content -Raw -LiteralPath $Path -Encoding UTF8 }
  if ($existing -ne $Content) {
    [IO.File]::WriteAllText($Path, $Content, $enc)
    Write-Host ("[OK] WROTE " + $Path) -ForegroundColor DarkGreen
  } else {
    Write-Host ("[OK] NO-CHANGE " + $Path) -ForegroundColor DarkCyan
  }
}

# Resolve RepoRoot safely
if (-not $RepoRoot) {
  $RepoRoot = (git rev-parse --show-toplevel).Trim()
}
if (-not $RepoRoot) { throw "RepoRoot not provided and git rev-parse failed (run inside repo or pass -RepoRoot)." }
if (-not (Test-Path -LiteralPath $RepoRoot)) { throw "RepoRoot not found: $RepoRoot" }
Set-Location $RepoRoot

$mgDir = Join-Path $RepoRoot "supabase\migrations"
EnsureDir $mgDir

if (-not $MigrationId) { $MigrationId = (Get-Date).ToUniversalTime().ToString("yyyyMMddHHmmss") }
$mgPath = Join-Path $mgDir ("{0}_rgsr_access_model_and_engine_registry_v1.sql" -f $MigrationId)

$sqlLines = New-Object System.Collections.Generic.List[string]
$sqlLines.Add('-- ============================================================')
$sqlLines.Add('-- RGSR: Canonical Access Model + Engine Registry (V1)')
$sqlLines.Add('-- Roles (who you are) ⟂ Plans (what you can do)')
$sqlLines.Add('-- Lanes are immutable-forward only: PRIVATE -> LAB -> REVIEW -> PUBLISHED')
$sqlLines.Add('-- Brand-new Supabase compatible (assumes auth.users exists).')
$sqlLines.Add('-- ============================================================')
$sqlLines.Add('')
$sqlLines.Add('begin;')
$sqlLines.Add('')
$sqlLines.Add('-- 0) Extensions (safe)')
$sqlLines.Add('create extension if not exists pgcrypto;')
$sqlLines.Add('')
$sqlLines.Add('-- 1) Schemas')
$sqlLines.Add('create schema if not exists rgsr;')
$sqlLines.Add('create schema if not exists engine_registry;')
$sqlLines.Add('')
$sqlLines.Add('-- 2) Enums')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_type where typname = ''rgsr_lane'') then')
$sqlLines.Add('    create type rgsr.rgsr_lane as enum (''PRIVATE'',''LAB'',''REVIEW'',''PUBLISHED'');')
$sqlLines.Add('  end if;')
$sqlLines.Add('  if not exists (select 1 from pg_type where typname = ''rgsr_role_id'') then')
$sqlLines.Add('    create type rgsr.rgsr_role_id as enum (''SYS_ADMIN'',''LAB_ADMIN'',''SCIENTIST'',''REVIEWER'',''OBSERVER'');')
$sqlLines.Add('  end if;')
$sqlLines.Add('  if not exists (select 1 from pg_type where typname = ''rgsr_plan_id'') then')
$sqlLines.Add('    create type rgsr.rgsr_plan_id as enum (''OBSERVER_FREE'',''RESEARCHER_PRO'',''LAB_STANDARD'',''INSTITUTION'');')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- 3) Identity: Role ⟂ Plan')
$sqlLines.Add('create table if not exists rgsr.user_profiles (')
$sqlLines.Add('  user_id        uuid primary key references auth.users(id) on delete cascade,')
$sqlLines.Add('  role_id        rgsr.rgsr_role_id not null default ''OBSERVER'',')
$sqlLines.Add('  plan_id        rgsr.rgsr_plan_id not null default ''OBSERVER_FREE'',')
$sqlLines.Add('  display_name   text,')
$sqlLines.Add('  created_at     timestamptz not null default now(),')
$sqlLines.Add('  updated_at     timestamptz not null default now()')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('create table if not exists rgsr.labs (')
$sqlLines.Add('  lab_id      uuid primary key default gen_random_uuid(),')
$sqlLines.Add('  name        text not null,')
$sqlLines.Add('  owner_id    uuid not null references auth.users(id) on delete cascade,')
$sqlLines.Add('  created_at  timestamptz not null default now()')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('create table if not exists rgsr.lab_members (')
$sqlLines.Add('  lab_id      uuid not null references rgsr.labs(lab_id) on delete cascade,')
$sqlLines.Add('  user_id     uuid not null references auth.users(id) on delete cascade,')
$sqlLines.Add('  is_admin    boolean not null default false,')
$sqlLines.Add('  created_at  timestamptz not null default now(),')
$sqlLines.Add('  primary key (lab_id, user_id)')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- updated_at helper')
$sqlLines.Add('create or replace function rgsr.tg_touch_updated_at()')
$sqlLines.Add('returns trigger language plpgsql as $$')
$sqlLines.Add('begin')
$sqlLines.Add('  new.updated_at = now();')
$sqlLines.Add('  return new;')
$sqlLines.Add('end $$;')
$sqlLines.Add('')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_trigger where tgname = ''tr_user_profiles_touch'') then')
$sqlLines.Add('    create trigger tr_user_profiles_touch')
$sqlLines.Add('    before update on rgsr.user_profiles')
$sqlLines.Add('    for each row execute function rgsr.tg_touch_updated_at();')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- 4) Capabilities + mappings')
$sqlLines.Add('create table if not exists rgsr.capabilities (')
$sqlLines.Add('  capability_id text primary key,')
$sqlLines.Add('  description   text not null')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('create table if not exists rgsr.plan_capabilities (')
$sqlLines.Add('  plan_id       rgsr.rgsr_plan_id not null,')
$sqlLines.Add('  capability_id text not null references rgsr.capabilities(capability_id) on delete cascade,')
$sqlLines.Add('  enabled       boolean not null default true,')
$sqlLines.Add('  primary key (plan_id, capability_id)')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('create table if not exists rgsr.role_capabilities (')
$sqlLines.Add('  role_id       rgsr.rgsr_role_id not null,')
$sqlLines.Add('  capability_id text not null references rgsr.capabilities(capability_id) on delete cascade,')
$sqlLines.Add('  enabled       boolean not null default true,')
$sqlLines.Add('  primary key (role_id, capability_id)')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- 5) Review assignments')
$sqlLines.Add('create table if not exists rgsr.review_assignments (')
$sqlLines.Add('  experiment_id uuid not null,')
$sqlLines.Add('  reviewer_id   uuid not null references auth.users(id) on delete cascade,')
$sqlLines.Add('  assigned_by   uuid not null references auth.users(id) on delete cascade,')
$sqlLines.Add('  created_at    timestamptz not null default now(),')
$sqlLines.Add('  primary key (experiment_id, reviewer_id)')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- 6) Experiments + forward-only lane')
$sqlLines.Add('create table if not exists rgsr.experiments (')
$sqlLines.Add('  experiment_id     uuid primary key default gen_random_uuid(),')
$sqlLines.Add('  engine_code       text not null default ''RGSR'',')
$sqlLines.Add('  phase_code        text not null,')
$sqlLines.Add('  lane              rgsr.rgsr_lane not null default ''PRIVATE'',')
$sqlLines.Add('  created_by        uuid not null references auth.users(id) on delete cascade,')
$sqlLines.Add('  lab_id            uuid references rgsr.labs(lab_id) on delete set null,')
$sqlLines.Add('  title             text,')
$sqlLines.Add('  notes             text,')
$sqlLines.Add('  conditions_profile text,')
$sqlLines.Add('  inputs_sha256     text,')
$sqlLines.Add('  outputs_sha256    text,')
$sqlLines.Add('  published_at      timestamptz,')
$sqlLines.Add('  created_at        timestamptz not null default now(),')
$sqlLines.Add('  updated_at        timestamptz not null default now()')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_trigger where tgname = ''tr_experiments_touch'') then')
$sqlLines.Add('    create trigger tr_experiments_touch')
$sqlLines.Add('    before update on rgsr.experiments')
$sqlLines.Add('    for each row execute function rgsr.tg_touch_updated_at();')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.lane_rank(l rgsr.rgsr_lane)')
$sqlLines.Add('returns int language sql immutable as $$')
$sqlLines.Add('  select case l')
$sqlLines.Add('    when ''PRIVATE'' then 1')
$sqlLines.Add('    when ''LAB'' then 2')
$sqlLines.Add('    when ''REVIEW'' then 3')
$sqlLines.Add('    when ''PUBLISHED'' then 4')
$sqlLines.Add('  end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.tg_enforce_lane_forward_only()')
$sqlLines.Add('returns trigger language plpgsql as $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if (tg_op = ''UPDATE'') then')
$sqlLines.Add('    if rgsr.lane_rank(new.lane) < rgsr.lane_rank(old.lane) then')
$sqlLines.Add('      raise exception ''RGSR lane is forward-only: % -> % is not allowed'', old.lane, new.lane')
$sqlLines.Add('        using errcode = ''check_violation'';')
$sqlLines.Add('    end if;')
$sqlLines.Add('    if new.lane = ''PUBLISHED'' and old.lane <> ''PUBLISHED'' then')
$sqlLines.Add('      new.published_at = coalesce(new.published_at, now());')
$sqlLines.Add('    end if;')
$sqlLines.Add('  end if;')
$sqlLines.Add('  return new;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_trigger where tgname = ''tr_experiments_lane_forward_only'') then')
$sqlLines.Add('    create trigger tr_experiments_lane_forward_only')
$sqlLines.Add('    before update of lane on rgsr.experiments')
$sqlLines.Add('    for each row execute function rgsr.tg_enforce_lane_forward_only();')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('-- 7) Condition Profiles')
$sqlLines.Add('create table if not exists rgsr.condition_profiles (')
$sqlLines.Add('  profile_id    uuid primary key default gen_random_uuid(),')
$sqlLines.Add('  profile_name  text not null unique,')
$sqlLines.Add('  profile_json  jsonb not null,')
$sqlLines.Add('  created_by    uuid not null references auth.users(id) on delete cascade,')
$sqlLines.Add('  created_at    timestamptz not null default now()')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- 8) Engine Registry')
$sqlLines.Add('create table if not exists engine_registry.engines (')
$sqlLines.Add('  engine_id     uuid primary key default gen_random_uuid(),')
$sqlLines.Add('  engine_code   text not null unique,')
$sqlLines.Add('  name          text not null,')
$sqlLines.Add('  status        text not null default ''ACTIVE'',')
$sqlLines.Add('  version       text,')
$sqlLines.Add('  created_at    timestamptz not null default now()')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('create table if not exists engine_registry.lanes (')
$sqlLines.Add('  engine_code   text not null references engine_registry.engines(engine_code) on delete cascade,')
$sqlLines.Add('  lane          rgsr.rgsr_lane not null,')
$sqlLines.Add('  description   text not null,')
$sqlLines.Add('  primary key (engine_code, lane)')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('create table if not exists engine_registry.engine_capabilities (')
$sqlLines.Add('  engine_code     text not null references engine_registry.engines(engine_code) on delete cascade,')
$sqlLines.Add('  capability_id   text not null references rgsr.capabilities(capability_id) on delete cascade,')
$sqlLines.Add('  primary key (engine_code, capability_id)')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- 9) Seeds')
$sqlLines.Add('insert into rgsr.capabilities (capability_id, description) values')
$sqlLines.Add('  (''RUN_PHASE_A'',        ''Run Phase A experiments''),')
$sqlLines.Add('  (''RUN_PHASE_B'',        ''Run Phase B perturbation tests''),')
$sqlLines.Add('  (''RUN_PHASE_C'',        ''Run Phase C coupling tests''),')
$sqlLines.Add('  (''RUN_PHASE_D'',        ''Run Phase D geometry grids''),')
$sqlLines.Add('  (''UPLOAD_GEOMETRY'',    ''Upload chamber models''),')
$sqlLines.Add('  (''DEFINE_CONDITIONS'',  ''Create condition profiles''),')
$sqlLines.Add('  (''EXPORT_RAW'',         ''Download raw data''),')
$sqlLines.Add('  (''PUBLISH'',            ''Move to PUBLISHED lane''),')
$sqlLines.Add('  (''REQUEST_REVIEW'',     ''Submit to reviewers''),')
$sqlLines.Add('  (''VIEW_PUBLISHED'',     ''See public results''),')
$sqlLines.Add('  (''TEAM_SHARE'',         ''Share inside a lab''),')
$sqlLines.Add('  (''API_ACCESS'',         ''Programmatic access''),')
$sqlLines.Add('  (''REVIEWER_ASSIGNMENT'',''Assign/manage reviewers'')')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- OBSERVER_FREE')
$sqlLines.Add('insert into rgsr.plan_capabilities(plan_id, capability_id, enabled) values')
$sqlLines.Add('  (''OBSERVER_FREE'',''VIEW_PUBLISHED'', true)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- RESEARCHER_PRO')
$sqlLines.Add('insert into rgsr.plan_capabilities(plan_id, capability_id, enabled) values')
$sqlLines.Add('  (''RESEARCHER_PRO'',''RUN_PHASE_A'', true),')
$sqlLines.Add('  (''RESEARCHER_PRO'',''UPLOAD_GEOMETRY'', true),')
$sqlLines.Add('  (''RESEARCHER_PRO'',''DEFINE_CONDITIONS'', true),')
$sqlLines.Add('  (''RESEARCHER_PRO'',''EXPORT_RAW'', true),')
$sqlLines.Add('  (''RESEARCHER_PRO'',''VIEW_PUBLISHED'', true)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- LAB_STANDARD')
$sqlLines.Add('insert into rgsr.plan_capabilities(plan_id, capability_id, enabled) values')
$sqlLines.Add('  (''LAB_STANDARD'',''RUN_PHASE_A'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''RUN_PHASE_B'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''TEAM_SHARE'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''REQUEST_REVIEW'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''EXPORT_RAW'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''DEFINE_CONDITIONS'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''UPLOAD_GEOMETRY'', true),')
$sqlLines.Add('  (''LAB_STANDARD'',''VIEW_PUBLISHED'', true)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- INSTITUTION')
$sqlLines.Add('insert into rgsr.plan_capabilities(plan_id, capability_id, enabled) values')
$sqlLines.Add('  (''INSTITUTION'',''RUN_PHASE_A'', true),')
$sqlLines.Add('  (''INSTITUTION'',''RUN_PHASE_B'', true),')
$sqlLines.Add('  (''INSTITUTION'',''RUN_PHASE_C'', true),')
$sqlLines.Add('  (''INSTITUTION'',''RUN_PHASE_D'', true),')
$sqlLines.Add('  (''INSTITUTION'',''PUBLISH'', true),')
$sqlLines.Add('  (''INSTITUTION'',''API_ACCESS'', true),')
$sqlLines.Add('  (''INSTITUTION'',''REVIEWER_ASSIGNMENT'', true),')
$sqlLines.Add('  (''INSTITUTION'',''REQUEST_REVIEW'', true),')
$sqlLines.Add('  (''INSTITUTION'',''EXPORT_RAW'', true),')
$sqlLines.Add('  (''INSTITUTION'',''DEFINE_CONDITIONS'', true),')
$sqlLines.Add('  (''INSTITUTION'',''UPLOAD_GEOMETRY'', true),')
$sqlLines.Add('  (''INSTITUTION'',''VIEW_PUBLISHED'', true),')
$sqlLines.Add('  (''INSTITUTION'',''TEAM_SHARE'', true)')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- SYS_ADMIN gets everything')
$sqlLines.Add('insert into rgsr.role_capabilities(role_id, capability_id, enabled)')
$sqlLines.Add('select ''SYS_ADMIN''::rgsr.rgsr_role_id, c.capability_id, true')
$sqlLines.Add('from rgsr.capabilities c')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- Engine registry seed')
$sqlLines.Add('insert into engine_registry.engines(engine_code, name, status, version)')
$sqlLines.Add('values (''RGSR'',''Resonant Geophysical Systems Research'',''ACTIVE'',''V1'')')
$sqlLines.Add('on conflict (engine_code) do nothing;')
$sqlLines.Add('')
$sqlLines.Add('insert into engine_registry.lanes(engine_code, lane, description) values')
$sqlLines.Add('  (''RGSR'',''PRIVATE'',''Only the creator can see it''),')
$sqlLines.Add('  (''RGSR'',''LAB'',''Visible to your lab/team''),')
$sqlLines.Add('  (''RGSR'',''REVIEW'',''Visible to assigned reviewers''),')
$sqlLines.Add('  (''RGSR'',''PUBLISHED'',''Public & immutable'')')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('insert into engine_registry.engine_capabilities(engine_code, capability_id)')
$sqlLines.Add('select ''RGSR'', capability_id from rgsr.capabilities')
$sqlLines.Add('on conflict do nothing;')
$sqlLines.Add('')
$sqlLines.Add('-- 10) Helper functions for RLS')
$sqlLines.Add('create or replace function rgsr.current_role()')
$sqlLines.Add('returns rgsr.rgsr_role_id')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select coalesce((select up.role_id from rgsr.user_profiles up where up.user_id = auth.uid()),')
$sqlLines.Add('                  ''OBSERVER''::rgsr.rgsr_role_id);')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.current_plan()')
$sqlLines.Add('returns rgsr.rgsr_plan_id')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select coalesce((select up.plan_id from rgsr.user_profiles up where up.user_id = auth.uid()),')
$sqlLines.Add('                  ''OBSERVER_FREE''::rgsr.rgsr_plan_id);')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.has_capability(cap text)')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  with me as (select rgsr.current_role() as role_id, rgsr.current_plan() as plan_id)')
$sqlLines.Add('  select exists (')
$sqlLines.Add('    select 1 from me')
$sqlLines.Add('    join rgsr.plan_capabilities pc on pc.plan_id = me.plan_id')
$sqlLines.Add('    where pc.capability_id = cap and pc.enabled')
$sqlLines.Add('  )')
$sqlLines.Add('  or exists (')
$sqlLines.Add('    select 1 from me')
$sqlLines.Add('    join rgsr.role_capabilities rc on rc.role_id = me.role_id')
$sqlLines.Add('    where rc.capability_id = cap and rc.enabled')
$sqlLines.Add('  );')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.is_sys_admin()')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select rgsr.current_role() = ''SYS_ADMIN''::rgsr.rgsr_role_id;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.is_lab_member(lab uuid)')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select exists (select 1 from rgsr.lab_members lm where lm.lab_id = lab and lm.user_id = auth.uid())')
$sqlLines.Add('     or exists (select 1 from rgsr.labs l where l.lab_id = lab and l.owner_id = auth.uid());')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.is_assigned_reviewer(experiment uuid)')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select exists (select 1 from rgsr.review_assignments ra where ra.experiment_id = experiment and ra.reviewer_id = auth.uid());')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.can_read_lane(l rgsr.rgsr_lane, created_by uuid, lab uuid, experiment uuid)')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select (rgsr.is_sys_admin())')
$sqlLines.Add('  or case l')
$sqlLines.Add('       when ''PUBLISHED'' then true')
$sqlLines.Add('       when ''PRIVATE'' then (auth.uid() = created_by) and rgsr.has_capability(''RUN_PHASE_A'')')
$sqlLines.Add('       when ''LAB'' then rgsr.is_lab_member(lab) and rgsr.has_capability(''TEAM_SHARE'')')
$sqlLines.Add('       when ''REVIEW'' then (')
$sqlLines.Add('         (rgsr.is_assigned_reviewer(experiment) and rgsr.current_role() in (''REVIEWER'',''SYS_ADMIN''))')
$sqlLines.Add('         or (rgsr.is_lab_member(lab) and rgsr.has_capability(''REQUEST_REVIEW''))')
$sqlLines.Add('       )')
$sqlLines.Add('     end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('create or replace function rgsr.can_write_lane_target(new_lane rgsr.rgsr_lane)')
$sqlLines.Add('returns boolean')
$sqlLines.Add('language sql stable as $$')
$sqlLines.Add('  select rgsr.is_sys_admin()')
$sqlLines.Add('  or case new_lane')
$sqlLines.Add('       when ''PRIVATE'' then true')
$sqlLines.Add('       when ''LAB'' then rgsr.has_capability(''TEAM_SHARE'')')
$sqlLines.Add('       when ''REVIEW'' then rgsr.has_capability(''REQUEST_REVIEW'')')
$sqlLines.Add('       when ''PUBLISHED'' then rgsr.has_capability(''PUBLISH'')')
$sqlLines.Add('     end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('-- 11) RLS enable + policies')
$sqlLines.Add('alter table rgsr.user_profiles enable row level security;')
$sqlLines.Add('alter table rgsr.labs enable row level security;')
$sqlLines.Add('alter table rgsr.lab_members enable row level security;')
$sqlLines.Add('alter table rgsr.experiments enable row level security;')
$sqlLines.Add('alter table rgsr.review_assignments enable row level security;')
$sqlLines.Add('alter table rgsr.condition_profiles enable row level security;')
$sqlLines.Add('')
$sqlLines.Add('-- user_profiles')
$sqlLines.Add('drop policy if exists up_select on rgsr.user_profiles;')
$sqlLines.Add('create policy up_select on rgsr.user_profiles for select to authenticated')
$sqlLines.Add('using (user_id = auth.uid() or rgsr.is_sys_admin());')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists up_insert on rgsr.user_profiles;')
$sqlLines.Add('create policy up_insert on rgsr.user_profiles for insert to authenticated')
$sqlLines.Add('with check (user_id = auth.uid() or rgsr.is_sys_admin());')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists up_update on rgsr.user_profiles;')
$sqlLines.Add('create policy up_update on rgsr.user_profiles for update to authenticated')
$sqlLines.Add('using (user_id = auth.uid() or rgsr.is_sys_admin())')
$sqlLines.Add('with check (user_id = auth.uid() or rgsr.is_sys_admin());')
$sqlLines.Add('')
$sqlLines.Add('-- labs')
$sqlLines.Add('drop policy if exists labs_select on rgsr.labs;')
$sqlLines.Add('create policy labs_select on rgsr.labs for select to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or owner_id = auth.uid()')
$sqlLines.Add('  or exists (select 1 from rgsr.lab_members lm where lm.lab_id = lab_id and lm.user_id = auth.uid())')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists labs_insert on rgsr.labs;')
$sqlLines.Add('create policy labs_insert on rgsr.labs for insert to authenticated')
$sqlLines.Add('with check (owner_id = auth.uid() or rgsr.is_sys_admin());')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists labs_update on rgsr.labs;')
$sqlLines.Add('create policy labs_update on rgsr.labs for update to authenticated')
$sqlLines.Add('using (owner_id = auth.uid() or rgsr.is_sys_admin())')
$sqlLines.Add('with check (owner_id = auth.uid() or rgsr.is_sys_admin());')
$sqlLines.Add('')
$sqlLines.Add('-- lab_members')
$sqlLines.Add('drop policy if exists lm_select on rgsr.lab_members;')
$sqlLines.Add('create policy lm_select on rgsr.lab_members for select to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or exists (select 1 from rgsr.labs l where l.lab_id = lab_id and l.owner_id = auth.uid())')
$sqlLines.Add('  or user_id = auth.uid()')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists lm_insert on rgsr.lab_members;')
$sqlLines.Add('create policy lm_insert on rgsr.lab_members for insert to authenticated')
$sqlLines.Add('with check (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or exists (select 1 from rgsr.labs l where l.lab_id = lab_id and l.owner_id = auth.uid())')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists lm_delete on rgsr.lab_members;')
$sqlLines.Add('create policy lm_delete on rgsr.lab_members for delete to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or exists (select 1 from rgsr.labs l where l.lab_id = lab_id and l.owner_id = auth.uid())')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- experiments')
$sqlLines.Add('drop policy if exists exp_select on rgsr.experiments;')
$sqlLines.Add('create policy exp_select on rgsr.experiments for select to authenticated')
$sqlLines.Add('using (rgsr.can_read_lane(lane, created_by, lab_id, experiment_id));')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists exp_insert on rgsr.experiments;')
$sqlLines.Add('create policy exp_insert on rgsr.experiments for insert to authenticated')
$sqlLines.Add('with check (')
$sqlLines.Add('  created_by = auth.uid()')
$sqlLines.Add('  and rgsr.can_write_lane_target(lane)')
$sqlLines.Add('  and (')
$sqlLines.Add('    (phase_code = ''PHASE_A'' and rgsr.has_capability(''RUN_PHASE_A''))')
$sqlLines.Add('    or (phase_code = ''PHASE_B'' and rgsr.has_capability(''RUN_PHASE_B''))')
$sqlLines.Add('    or (phase_code = ''PHASE_C'' and rgsr.has_capability(''RUN_PHASE_C''))')
$sqlLines.Add('    or (phase_code = ''PHASE_D'' and rgsr.has_capability(''RUN_PHASE_D''))')
$sqlLines.Add('  )')
$sqlLines.Add('  and (lab_id is null or rgsr.is_lab_member(lab_id))')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists exp_update on rgsr.experiments;')
$sqlLines.Add('create policy exp_update on rgsr.experiments for update to authenticated')
$sqlLines.Add('using (')
$sqlLines.Add('  rgsr.is_sys_admin()')
$sqlLines.Add('  or created_by = auth.uid()')
$sqlLines.Add('  or (lab_id is not null and rgsr.is_lab_member(lab_id))')
$sqlLines.Add(')')
$sqlLines.Add('with check (')
$sqlLines.Add('  rgsr.can_write_lane_target(lane)')
$sqlLines.Add('  and (lab_id is null or rgsr.is_lab_member(lab_id))')
$sqlLines.Add(');')
$sqlLines.Add('')
$sqlLines.Add('-- review_assignments')
$sqlLines.Add('drop policy if exists ra_select on rgsr.review_assignments;')
$sqlLines.Add('create policy ra_select on rgsr.review_assignments for select to authenticated')
$sqlLines.Add('using (rgsr.is_sys_admin() or reviewer_id = auth.uid() or assigned_by = auth.uid());')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists ra_insert on rgsr.review_assignments;')
$sqlLines.Add('create policy ra_insert on rgsr.review_assignments for insert to authenticated')
$sqlLines.Add('with check (rgsr.is_sys_admin() or rgsr.has_capability(''REVIEWER_ASSIGNMENT''));')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists ra_delete on rgsr.review_assignments;')
$sqlLines.Add('create policy ra_delete on rgsr.review_assignments for delete to authenticated')
$sqlLines.Add('using (rgsr.is_sys_admin() or rgsr.has_capability(''REVIEWER_ASSIGNMENT''));')
$sqlLines.Add('')
$sqlLines.Add('-- condition_profiles')
$sqlLines.Add('drop policy if exists cp_select on rgsr.condition_profiles;')
$sqlLines.Add('create policy cp_select on rgsr.condition_profiles for select to authenticated')
$sqlLines.Add('using (true);')
$sqlLines.Add('')
$sqlLines.Add('drop policy if exists cp_insert on rgsr.condition_profiles;')
$sqlLines.Add('create policy cp_insert on rgsr.condition_profiles for insert to authenticated')
$sqlLines.Add('with check (created_by = auth.uid() and rgsr.has_capability(''DEFINE_CONDITIONS''));')
$sqlLines.Add('')
$sqlLines.Add('-- 12) Auto-provision user_profiles on signup')
$sqlLines.Add('create or replace function rgsr.handle_new_user()')
$sqlLines.Add('returns trigger')
$sqlLines.Add('language plpgsql')
$sqlLines.Add('security definer')
$sqlLines.Add('set search_path = rgsr, public, auth as $$')
$sqlLines.Add('begin')
$sqlLines.Add('  insert into rgsr.user_profiles (user_id, role_id, plan_id, display_name)')
$sqlLines.Add('  values (new.id, ''OBSERVER'', ''OBSERVER_FREE'', coalesce(new.email, new.phone))')
$sqlLines.Add('  on conflict (user_id) do nothing;')
$sqlLines.Add('  return new;')
$sqlLines.Add('end;')
$sqlLines.Add('$$;')
$sqlLines.Add('')
$sqlLines.Add('do $$')
$sqlLines.Add('begin')
$sqlLines.Add('  if not exists (select 1 from pg_trigger where tgname = ''tr_rgsr_on_auth_user_created'') then')
$sqlLines.Add('    create trigger tr_rgsr_on_auth_user_created')
$sqlLines.Add('    after insert on auth.users')
$sqlLines.Add('    for each row execute function rgsr.handle_new_user();')
$sqlLines.Add('  end if;')
$sqlLines.Add('end$$;')
$sqlLines.Add('')
$sqlLines.Add('commit;')
$sqlLines.Add('')
$sqlLines.Add('-- ============================================================')
$sqlLines.Add('-- End migration')
$sqlLines.Add('-- ============================================================')
$sql = ($sqlLines -join "`r`n") + "`r`n"

WriteUtf8NoBomIfChanged $mgPath $sql
Write-Host ("[OK] MIGRATION READY: " + $mgPath) -ForegroundColor Green

if ($LinkProject) {
  if (-not $ProjectRef) {
    Write-Host "[NOTE] Paste Supabase Project Ref (Settings -> General -> Project Ref)" -ForegroundColor Yellow
    $ProjectRef = Read-Host "ProjectRef"
  }
  if (-not $ProjectRef) { throw "ProjectRef is required for link." }
  supabase link --project-ref $ProjectRef
}

if ($ApplyRemote) {
  supabase db push
}

Write-Host "✅ RGSR ACCESS MODEL PIPELINE COMPLETE" -ForegroundColor Green

